/-
Copyright (c) 2026 Ian Klatzco. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ian Klatzco
-/
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.SemidirectProduct
import OddOrder.Mathlib.GroupTheory.Hall

/-!
# Coprime action on a finite group

The coprime-action suite: the fixed-point and Hall-subgroup theory of a group `A`
acting on a finite group `G` with `(Nat.card A).Coprime (Nat.card G)`.  These lemmas
(MathComp's `coprime_quotient_cent`, `coprime_cent_prod`, `coprime_commGid`,
`coprime_abelian_cent_dprod`, `coprime_Hall_exists`, `coprime_Hall_trans`) underpin
most of the local analysis in the odd order theorem.

## The API decision

A coprime action is encoded **externally**, as
`[Group A] [Group G] [MulDistribMulAction A G]` together with an explicit coprimality
hypothesis `(Nat.card A).Coprime (Nat.card G)` (plus `[Finite A]`, `[Finite G]` as
needed).  Rationale:

* `MulDistribMulAction` is Mathlib-native: it already comes with the fixed-point
  subgroup `FixedPoints.subgroup A G` (which we use for MathComp's `'C_G(A)` — we do
  *not* define our own), the monoid homomorphisms `MulDistribMulAction.toMonoidHom`
  and `MulDistribMulAction.toMulAut`, and the quotient-action machinery in
  `Mathlib/GroupTheory/GroupAction/OfQuotient.lean`.
* It avoids fixing `A` to be a subgroup of `MulAut G`, so the same lemmas apply
  whether `A` is an abstract group, a quotient acting on fixed points, or a subgroup
  acting by conjugation.
* **Internal actions** (`A`, `G` subgroups of a common group with
  `A ≤ Subgroup.normalizer G`, the situation of MathComp's `[~: G, A]`, `'C_G(A)`)
  are recovered through the conjugation action: see
  `Subgroup.normalizerMulDistribMulAction` below for the bridge.  Further internal
  transfer lemmas are deliberately deferred to the files that need them (Task-8-adjacent).

On top of the action we introduce:

* `Subgroup.SMulInvariant A H`: the subgroup `H` is stable under the action of `A`
  (MathComp: `A \subset 'N(H)` for internal actions).  This is a class, mirroring
  `Subgroup.Normal`, so that instances can transport it (characteristic subgroups
  are invariant, quotient actions exist, an invariant subgroup is itself acted on).
* `Subgroup.actionCommutator A H`: the commutator `[H, A]` of the action, the
  subgroup generated by `g⁻¹ * (a • g)` for `g ∈ H`, `a : A`.  It is *relative*
  (it takes a subgroup argument, MathComp-style) so that the iterated commutator
  `[G, A, A]` is expressible without subtype gymnastics; the full commutator
  `[G, A]` is `Subgroup.actionCommutator A (⊤ : Subgroup G)`.
* For an invariant normal subgroup `N`, the induced `MulDistribMulAction A (G ⧸ N)`
  (through Mathlib's `MulAction.QuotientAction`) and for an invariant subgroup `H`
  the restricted `MulDistribMulAction A ↥H`, both as instances.

## Main results

All six take a coprimality hypothesis; `G` is finite throughout.

* `coprime_fixedPoints_quotient_surjective` (+ the subgroup-equality form
  `coprime_fixedPoints_quotient_eq`): for an `A`-invariant normal *solvable*
  subgroup `N` with `(Nat.card A).Coprime (Nat.card N)`, every `A`-fixed point of
  `G ⧸ N` lifts to an `A`-fixed point of `G`.  MathComp: `coprime_quotient_cent`
  (`'C_G(A) / N = 'C_(G / N)(A / N)`), which likewise assumes `N` solvable; by
  Feit–Thompson one of `N`, `A` is always solvable, but that is not available here.
* `coprime_cent_prod`: for solvable `G`, `[G, A] * C_G(A) = G`, stated as
  `actionCommutator A ⊤ ⊔ FixedPoints.subgroup A G = ⊤` (the join of a normal
  subgroup is the setwise product, `Subgroup.normal_mul`).  MathComp:
  `coprime_cent_prod`; B&G 1.6(a).
* `coprime_commutator_eq`: for solvable `G`, `[G, A, A] = [G, A]`.  MathComp:
  `coprime_commGid`, which also assumes `G` solvable (the fully general coprime
  statement needs Glauberman/Feit–Thompson input).  B&G 1.6(b).
* `coprime_abelian_cent_dprod`: for abelian `G`, `G = [G, A] × C_G(A)` as an
  internal direct product, stated as
  `IsComplement' (actionCommutator A ⊤) (FixedPoints.subgroup A G)`; both factors
  are normal (`G` is abelian), so this is Mathlib's internal-direct-product idiom.
  MathComp: `coprime_abelian_cent_dprod`; B&G 1.6(d).
* `coprime_hall_exists`: for solvable `G`, an `A`-invariant Hall π-subgroup exists.
  MathComp: `coprime_Hall_exists` (whose `solvable A` alternative via Feit–Thompson
  is not ported: we require `G` solvable, `A` arbitrary).
* `coprime_hall_trans`: any two `A`-invariant Hall π-subgroups of a solvable `G`
  are conjugate by an element of `FixedPoints.subgroup A G`.  MathComp:
  `coprime_Hall_trans`.

MathComp's `coprime_Hall_subset` and the Glauberman-lemma variants are out of scope
here and recorded as future work in `docs/NAME_MAP.md`.

The proofs of the Hall-subgroup statements transport the action to the semidirect
product `G ⋊[φ] A` (with `φ := MulDistribMulAction.toMulAut A G`), where
`A`-invariant subgroups of `G` become subgroups normalized by the `A`-factor and
the Schur–Zassenhaus and Frattini-style conjugation arguments of
`OddOrder.Mathlib.GroupTheory.SchurZassenhaus` apply.
-/

namespace Subgroup

/-!
### `A`-invariant subgroups
-/

section SMulInvariant

variable {G : Type*} [Group G]

/-- A subgroup `H` of `G` is *`A`-invariant* if it is stable under the action of every
element of `A`.  For internal actions (conjugation) this corresponds to MathComp's
`A \subset 'N(H)`. -/
class SMulInvariant (A : Type*) {G : Type*} [Group G] [SMul A G] (H : Subgroup G) :
    Prop where
  /-- The action of any `a : A` maps `H` into itself. -/
  smul_mem : ∀ (a : A) ⦃g : G⦄, g ∈ H → a • g ∈ H

/-- For a group action, an invariant subgroup contains `a • g` iff it contains `g`. -/
theorem SMulInvariant.smul_mem_iff {A : Type*} [Group A] [MulAction A G]
    {H : Subgroup G} [H.SMulInvariant A] (a : A) {g : G} : a • g ∈ H ↔ g ∈ H :=
  ⟨fun h => by simpa using SMulInvariant.smul_mem a⁻¹ h, fun h => SMulInvariant.smul_mem a h⟩

variable {A : Type*} [Group A] [MulDistribMulAction A G]

/-- Characteristic subgroups are invariant under any action by automorphisms. -/
instance (priority := 100) SMulInvariant.of_characteristic (H : Subgroup G)
    [H.Characteristic] : H.SMulInvariant A where
  smul_mem a g hg := by
    have h := characteristic_iff_le_comap.mp ‹H.Characteristic›
      (MulDistribMulAction.toMulEquiv G a)
    simpa [mem_comap] using h hg

/-- The fixed points of the action form an invariant subgroup (the action on them is
trivial). -/
instance : (FixedPoints.subgroup A G).SMulInvariant A where
  smul_mem a g hg := by rw [hg a]; exact hg

/-- An invariant subgroup of an invariant subgroup maps forward: the image under the
inclusion of an invariant subgroup is invariant.  Stated for a general equivariant
homomorphism. -/
theorem SMulInvariant.map {G' : Type*} [Group G'] [SMul A G'] {H : Subgroup G}
    [H.SMulInvariant A] (f : G →* G') (hf : ∀ (a : A) (g : G), f (a • g) = a • f g) :
    (H.map f).SMulInvariant A where
  smul_mem a g hg := by
    obtain ⟨h, hh, rfl⟩ := hg
    exact ⟨a • h, SMulInvariant.smul_mem a hh, hf a h⟩

/-- The preimage of an invariant subgroup under an equivariant homomorphism is
invariant. -/
theorem SMulInvariant.comap {G' : Type*} [Group G'] [SMul A G'] {H : Subgroup G'}
    [H.SMulInvariant A] (f : G →* G') (hf : ∀ (a : A) (g : G), f (a • g) = a • f g) :
    (H.comap f).SMulInvariant A where
  smul_mem a g hg := by
    rw [mem_comap, hf a g]
    exact SMulInvariant.smul_mem a hg

open scoped commutatorElement in
/-- The commutator of two invariant subgroups is invariant:
`a • ⁅g, h⁆ = ⁅a • g, a • h⁆`. -/
instance commutator_smulInvariant (H K : Subgroup G) [H.SMulInvariant A]
    [K.SMulInvariant A] : (⁅H, K⁆ : Subgroup G).SMulInvariant A := by
  constructor
  intro a n hn
  rw [commutator_def] at hn ⊢
  induction hn using closure_induction with
  | mem x hx =>
    obtain ⟨p, hp, q, hq, rfl⟩ := hx
    have key : a • ⁅p, q⁆ = ⁅a • p, a • q⁆ :=
      map_commutatorElement (MulDistribMulAction.toMonoidHom G a) p q
    rw [key]
    exact subset_closure
      ⟨a • p, SMulInvariant.smul_mem a hp, a • q, SMulInvariant.smul_mem a hq, rfl⟩
  | one => simp
  | mul x y _ _ hx hy =>
    rw [smul_mul']
    exact mul_mem hx hy
  | inv x _ hx =>
    rw [smul_inv']
    exact inv_mem hx

end SMulInvariant

/-!
### The induced actions on an invariant subgroup and on the quotient by an
invariant normal subgroup
-/

section InducedActions

variable {A G : Type*} [Group G]

/-- The action of `A` descends to the coset space `G ⧸ N` of an `A`-invariant
subgroup `N`. -/
instance (priority := 100) [Monoid A] [MulDistribMulAction A G] (N : Subgroup G)
    [N.SMulInvariant A] : MulAction.QuotientAction A N where
  inv_mul_mem a {g₁ g₂} h := by
    rw [← smul_inv', ← smul_mul']
    exact SMulInvariant.smul_mem a h

/-- The action of `A` on the quotient of `G` by an `A`-invariant normal subgroup, as
a `MulDistribMulAction`.  The underlying `MulAction` is Mathlib's
`MulAction.quotient`, so `MulAction.Quotient.smul_mk` applies: `a • ↑g = ↑(a • g)`. -/
instance [Monoid A] [MulDistribMulAction A G] (N : Subgroup G) [N.Normal]
    [N.SMulInvariant A] : MulDistribMulAction A (G ⧸ N) where
  __ := (inferInstance : MulAction A (G ⧸ N))
  smul_mul a x y :=
    QuotientGroup.induction_on x fun g =>
      QuotientGroup.induction_on y fun h => congrArg QuotientGroup.mk (smul_mul' a g h)
  smul_one a := congrArg QuotientGroup.mk (smul_one a)

/-- The restriction of the action of `A` to an `A`-invariant subgroup. -/
instance [Monoid A] [MulDistribMulAction A G] (H : Subgroup G) [H.SMulInvariant A] :
    MulDistribMulAction A ↥H where
  smul a g := ⟨a • ↑g, SMulInvariant.smul_mem a g.2⟩
  one_smul g := Subtype.ext (one_smul A (g : G))
  mul_smul a b g := Subtype.ext (mul_smul a b (g : G))
  smul_mul a g h := Subtype.ext (smul_mul' a (g : G) (h : G))
  smul_one a := Subtype.ext (smul_one a)

@[simp]
theorem coe_smul [Monoid A] [MulDistribMulAction A G] {H : Subgroup G}
    [H.SMulInvariant A] (a : A) (g : H) : ((a • g : H) : G) = a • (g : G) :=
  rfl

/-- **Internal-action bridge**: a subgroup `A` of `G` normalizing a subgroup `H` acts
on `H` by conjugation, recovering MathComp's internal action from the external
`MulDistribMulAction` interface.  This is a `def`, not an instance, since it depends
on the hypothesis `A ≤ normalizer (H : Set G)`. -/
abbrev normalizerMulDistribMulAction {G : Type*} [Group G] {A H : Subgroup G}
    (hAH : A ≤ normalizer (H : Set G)) : MulDistribMulAction A H :=
  MulDistribMulAction.compHom H (Subgroup.inclusion hAH)

end InducedActions

/-!
### The commutator `[H, A]` of an action

`Subgroup.actionCommutator A H` is the subgroup generated by the "commutators"
`g⁻¹ * (a • g)` of the action, for `g ∈ H`.  For the conjugation action this is the
usual commutator of subgroups.  It is defined relative to a subgroup `H` (MathComp
style) so that the iterated commutator `[G, A, A]` is
`actionCommutator A (actionCommutator A ⊤)`.
-/

section ActionCommutator

variable {G : Type*} [Group G]

/-- The commutator `[H, A]` of an action: the subgroup generated by
`g⁻¹ * (a • g)` for `g ∈ H` and `a : A`.  MathComp: `[~: H, A]` (internal form). -/
def actionCommutator (A : Type*) [SMul A G] (H : Subgroup G) : Subgroup G :=
  closure {x | ∃ (a : A) (g : G), g ∈ H ∧ x = g⁻¹ * (a • g)}

variable {A : Type*}

theorem inv_mul_smul_mem_actionCommutator [SMul A G] {H : Subgroup G} (a : A) {g : G}
    (hg : g ∈ H) : g⁻¹ * (a • g) ∈ H.actionCommutator A :=
  subset_closure ⟨a, g, hg, rfl⟩

theorem actionCommutator_le [SMul A G] {H K : Subgroup G} :
    H.actionCommutator A ≤ K ↔ ∀ (a : A), ∀ g ∈ H, g⁻¹ * (a • g) ∈ K := by
  rw [actionCommutator, closure_le]
  constructor
  · exact fun h a g hg => h ⟨a, g, hg, rfl⟩
  · rintro h x ⟨a, g, hg, rfl⟩
    exact h a g hg

/-- The commutator of the action on an invariant subgroup is contained in it. -/
theorem actionCommutator_le_self [Monoid A] [MulAction A G] (H : Subgroup G)
    [H.SMulInvariant A] : H.actionCommutator A ≤ H :=
  actionCommutator_le.mpr fun a _ hg => H.mul_mem (H.inv_mem hg) (SMulInvariant.smul_mem a hg)

/-- The full action commutator `[G, A] = actionCommutator A ⊤` is a normal subgroup:
conjugating a generator gives `y⁻¹ * (g⁻¹ * a • g) * y =
((g * y)⁻¹ * a • (g * y)) * (y⁻¹ * a • y)⁻¹`. -/
instance actionCommutator_normal [Monoid A] [MulDistribMulAction A G] :
    (actionCommutator A (⊤ : Subgroup G)).Normal := by
  constructor
  intro n hn y
  rw [show y * n * y⁻¹ = (y⁻¹)⁻¹ * n * y⁻¹ by rw [inv_inv]]
  generalize y⁻¹ = z
  induction hn using closure_induction with
  | mem x hx =>
    obtain ⟨a, g, -, rfl⟩ := hx
    have key : z⁻¹ * (g⁻¹ * a • g) * z
        = ((g * z)⁻¹ * a • (g * z)) * (z⁻¹ * a • z)⁻¹ := by
      simp only [smul_mul', mul_inv_rev]
      group
    rw [key]
    exact mul_mem (inv_mul_smul_mem_actionCommutator a (mem_top _))
      (inv_mem (inv_mul_smul_mem_actionCommutator a (mem_top _)))
  | one => simp
  | mul x y' _ _ hx hy =>
    rw [show z⁻¹ * (x * y') * z = (z⁻¹ * x * z) * (z⁻¹ * y' * z) by group]
    exact mul_mem hx hy
  | inv x _ hx =>
    rw [show z⁻¹ * x⁻¹ * z = (z⁻¹ * x * z)⁻¹ by group]
    exact inv_mem hx

/-- The commutator of the action on an invariant subgroup is invariant:
`a' • (g⁻¹ * a • g) = (a' • g)⁻¹ * ((a' * a * a'⁻¹) • (a' • g))`. -/
instance actionCommutator_smulInvariant [Group A] [MulDistribMulAction A G]
    (H : Subgroup G) [H.SMulInvariant A] : (H.actionCommutator A).SMulInvariant A := by
  constructor
  intro b n hn
  induction hn using closure_induction with
  | mem x hx =>
    obtain ⟨a, g, hg, rfl⟩ := hx
    have key : b • (g⁻¹ * a • g) = (b • g)⁻¹ * ((b * a * b⁻¹) • (b • g)) := by
      rw [smul_mul', smul_inv', mul_smul, mul_smul, inv_smul_smul]
    rw [key]
    exact inv_mul_smul_mem_actionCommutator _ (SMulInvariant.smul_mem b hg)
  | one => simp
  | mul x y _ _ hx hy =>
    rw [smul_mul']
    exact mul_mem hx hy
  | inv x _ hx =>
    rw [smul_inv']
    exact inv_mem hx

end ActionCommutator

end Subgroup

/-!
### The coprime action suite
-/

open Subgroup

section CoprimeAction

variable {A G : Type*} [Group A] [Group G] [MulDistribMulAction A G]

/-!
#### Fixed-point lifting

The crux of the suite: an `A`-fixed coset `gN` of an invariant subgroup `N` contains
an `A`-fixed element, provided the action is coprime and `N` is solvable.  The
abelian case is the classical averaging argument, phrased multiplicatively: the map
`ν a := g⁻¹ * (a • g)` is a cocycle `A → N`; its "average" `σ := ∏ a, ν a` satisfies
`b • σ = (ν b)⁻¹ ^ |A| * σ`, so the `|A|`-th root `τ` of `σ` (which exists and is
unique by coprimality, `powCoprime`) satisfies `b • τ = (ν b)⁻¹ * τ`, making `g * τ`
a fixed point of the coset.  The solvable case follows by induction on `Nat.card N`
along the derived series.
-/

open scoped commutatorElement

section FixedPointLifting

open scoped IsMulCommutative in
/-- Abelian case of fixed-point lifting, in coset form: if the coset `g * N` of a
finite abelian invariant subgroup `N` is `A`-stable (i.e. `g⁻¹ * (a • g) ∈ N` for
all `a`) and the action is coprime, then the coset contains an `A`-fixed point. -/
private theorem exists_mul_mem_fixedPoints_of_isMulCommutative [Finite A]
    {N : Subgroup G} [N.SMulInvariant A] [Finite N] [IsMulCommutative N]
    (hco : (Nat.card A).Coprime (Nat.card N)) {g : G}
    (hg : ∀ a : A, g⁻¹ * (a • g) ∈ N) :
    ∃ x ∈ N, g * x ∈ FixedPoints.subgroup A G := by
  have := Fintype.ofFinite A
  -- The cocycle of the `A`-stable coset `g * N`.
  set ν : A → N := fun a => ⟨g⁻¹ * (a • g), hg a⟩ with hν
  have hcocycle : ∀ a b : A, ν (a * b) = ν a * a • ν b := by
    intro a b
    refine Subtype.ext ?_
    change g⁻¹ * ((a * b) • g) = (g⁻¹ * (a • g)) * (a • (g⁻¹ * (b • g)))
    rw [smul_mul', smul_inv', mul_smul]
    group
  -- The average of the cocycle.
  set σ : N := ∏ a : A, ν a with hσ
  have hσsmul : ∀ b : A, b • σ = (ν b)⁻¹ ^ Nat.card A * σ := by
    intro b
    have h1 : b • σ = ∏ a : A, b • ν a :=
      map_prod (MulDistribMulAction.toMonoidHom N b) ν Finset.univ
    have h2 : ∀ a : A, b • ν a = (ν b)⁻¹ * ν (b * a) := fun a => by
      rw [hcocycle b a, inv_mul_cancel_left]
    calc b • σ = ∏ a : A, ((ν b)⁻¹ * ν (b * a)) := by
          rw [h1]; exact Finset.prod_congr rfl fun a _ => h2 a
      _ = (∏ _a : A, (ν b)⁻¹) * ∏ a : A, ν (b * a) := Finset.prod_mul_distrib
      _ = (ν b)⁻¹ ^ Nat.card A * σ := by
          rw [Finset.prod_const, Finset.card_univ, Nat.card_eq_fintype_card, hσ]
          congr 1
          simpa using Equiv.prod_comp (Equiv.mulLeft b) ν
  -- The `|A|`-th root `τ` of `σ` translates `g` into the fixed points.
  set τ : N := (powCoprime hco.symm).symm σ with hτ
  have hτpow : τ ^ Nat.card A = σ := by
    have h := (powCoprime hco.symm).apply_symm_apply σ
    rwa [powCoprime_apply] at h
  have hsmulτ : ∀ a : A, a • τ = (ν a)⁻¹ * τ := by
    intro a
    refine (powCoprime hco.symm).injective ?_
    rw [powCoprime_apply, powCoprime_apply, ← smul_pow', hτpow, hσsmul a, mul_pow, hτpow]
  refine ⟨τ, τ.2, fun a => ?_⟩
  calc a • (g * (τ : G)) = (a • g) * ((a • τ : N) : G) := by rw [smul_mul']; rfl
    _ = (a • g) * ((g⁻¹ * (a • g))⁻¹ * (τ : G)) := by rw [hsmulτ a]; push_cast; rfl
    _ = g * (τ : G) := by group

/-- The commutator subgroup of a solvable subgroup is strictly smaller (the ambient
group need not be solvable).  This is `IsSolvable.commutator_lt_of_ne_bot` with the
solvability hypothesis on the subgroup itself. -/
private theorem commutator_lt_of_isSolvable {N : Subgroup G} [IsSolvable N]
    (hbot : N ≠ ⊥) : ⁅N, N⁆ < N := by
  rw [← N.nontrivial_iff_ne_bot] at hbot
  rw [← N.range_subtype, MonoidHom.range_eq_map, ← map_commutator,
    map_subtype_lt_map_subtype]
  exact IsSolvable.commutator_lt_top_of_nontrivial N

universe u v

/-- Auxiliary strong induction on `Nat.card N` for
`coprime_fixedPoints_quotient_surjective`, in coset form: an `A`-stable coset of a
finite solvable invariant normal subgroup contains a fixed point.  The bound `n` is
explicit so that the induction hypothesis applies to the quotient `G ⧸ ⁅N, N⁆`
(which lives in a different type). -/
private theorem exists_mul_mem_fixedPoints_aux (A : Type v) [Group A] [Finite A]
    (n : ℕ) :
    ∀ (G : Type u) [Group G] [MulDistribMulAction A G],
      ∀ (N : Subgroup G) [N.Normal] [N.SMulInvariant A] [Finite N] [IsSolvable N],
      Nat.card N ≤ n → (Nat.card A).Coprime (Nat.card N) →
      ∀ {g : G}, (∀ a : A, g⁻¹ * (a • g) ∈ N) →
      ∃ x ∈ N, g * x ∈ FixedPoints.subgroup A G := by
  induction n with
  | zero =>
    intro G _ _ N _ _ _ _ hn
    exact absurd (Nat.le_zero.mp hn) Nat.card_pos.ne'
  | succ n ih =>
    intro G _ _ N _ _ _ _ hn hco g hg
    by_cases habel : ⁅N, N⁆ = ⊥
    -- Base case: `N` abelian.
    · haveI : IsMulCommutative N := ⟨⟨fun x y => Subtype.ext <| by
        have h1 : ⁅(x : G), (y : G)⁆ ∈ ⁅N, N⁆ := commutator_mem_commutator x.2 y.2
        rwa [habel, mem_bot, commutatorElement_eq_one_iff_mul_comm] at h1⟩⟩
      exact exists_mul_mem_fixedPoints_of_isMulCommutative hco hg
    -- Inductive case: pass to `G ⧸ N'` with `N' := ⁅N, N⁆`, where the image of `N`
    -- is abelian; lift the resulting fixed point, then correct inside `N'`.
    · obtain ⟨N', hN'⟩ : ∃ N', N' = ⁅N, N⁆ := ⟨_, rfl⟩
      haveI : N'.Normal := hN' ▸ commutator_normal N N
      haveI : N'.SMulInvariant A := hN' ▸ commutator_smulInvariant N N
      have hN'le : N' ≤ N := hN' ▸ commutator_le.mpr fun p hp q hq =>
        N.mul_mem (N.mul_mem (N.mul_mem hp hq) (N.inv_mem hp)) (N.inv_mem hq)
      haveI : Finite N' := Finite.of_injective _ (inclusion_injective hN'le)
      haveI : IsSolvable N' := isSolvable_of_le ‹IsSolvable N› hN'le
      have hN'ne : N' ≠ ⊥ := hN' ▸ habel
      have hNne : N ≠ ⊥ := fun h => hN'ne (le_bot_iff.mp (h ▸ hN'le))
      have hN'lt : N' < N := hN' ▸ commutator_lt_of_isSolvable hNne
      have hcolt : Nat.card N' < Nat.card N :=
        lt_of_le_of_ne (card_le_of_le hN'le) fun h =>
          hN'lt.ne (eq_of_le_of_card_ge hN'le h.ge)
      -- The image of `N` in `G ⧸ N'` is a finite abelian invariant subgroup.
      obtain ⟨Nbar, hNbar⟩ : ∃ Nbar, Nbar = N.map (QuotientGroup.mk' N') := ⟨_, rfl⟩
      haveI : Nbar.SMulInvariant A := hNbar ▸ SMulInvariant.map (QuotientGroup.mk' N')
        fun a x => (MulAction.Quotient.smul_mk N' a x).symm
      haveI : Finite Nbar := by
        rw [hNbar]
        exact Finite.of_surjective _ ((QuotientGroup.mk' N').subgroupMap_surjective N)
      haveI : IsMulCommutative Nbar := by
        constructor
        constructor
        rintro ⟨x, hx⟩ ⟨y, hy⟩
        rw [hNbar] at hx hy
        obtain ⟨p, hp, rfl⟩ := hx
        obtain ⟨q, hq, rfl⟩ := hy
        refine Subtype.ext ?_
        change QuotientGroup.mk' N' p * QuotientGroup.mk' N' q
          = QuotientGroup.mk' N' q * QuotientGroup.mk' N' p
        rw [← map_mul, ← map_mul]
        refine QuotientGroup.eq.mpr ?_
        have h : (p * q)⁻¹ * (q * p) = ⁅q⁻¹, p⁻¹⁆ := by
          rw [commutatorElement_def]; group
        rw [h, hN']
        exact commutator_mem_commutator (N.inv_mem hq) (N.inv_mem hp)
      -- Push the coset condition to the quotient and lift a fixed point there.
      have hgbar : ∀ a : A, ((g : G ⧸ N'))⁻¹ * (a • (g : G ⧸ N')) ∈ Nbar := by
        intro a
        rw [hNbar]
        refine ⟨g⁻¹ * (a • g), hg a, ?_⟩
        rw [map_mul, map_inv]
        rfl
      have hcobar : (Nat.card A).Coprime (Nat.card Nbar) := by
        refine hco.coprime_dvd_right ?_
        rw [hNbar]
        exact N.card_map_dvd _
      obtain ⟨nb, hnb, hfix1⟩ := exists_mul_mem_fixedPoints_of_isMulCommutative
        (N := Nbar) hcobar hgbar
      rw [hNbar] at hnb
      obtain ⟨x₁, hx₁, hx₁eq⟩ := hnb
      have hfix1' : ((g * x₁ : G) : G ⧸ N') ∈ FixedPoints.subgroup A (G ⧸ N') := by
        have h : ((g * x₁ : G) : G ⧸ N') = (g : G ⧸ N') * nb := by rw [← hx₁eq]; rfl
        rw [h]
        exact hfix1
      have hg₁ : ∀ a : A, (g * x₁)⁻¹ * (a • (g * x₁)) ∈ N' := by
        intro a
        have h := hfix1' a
        rw [MulAction.Quotient.smul_mk] at h
        exact QuotientGroup.eq.mp h.symm
      -- Correct the lift inside `N'` by induction.
      obtain ⟨x₂, hx₂, hfix₂⟩ := ih G N' (Nat.le_of_lt_succ (hcolt.trans_le hn))
        (hco.coprime_dvd_right (card_dvd_of_le hN'le)) hg₁
      exact ⟨x₁ * x₂, N.mul_mem hx₁ (hN'le hx₂), by rwa [← mul_assoc]⟩

end FixedPointLifting

/-- **Fixed points lift along coprime quotients** (surjectivity form): if `N` is an
`A`-invariant normal subgroup of `G` which is finite, *solvable* and of order coprime
to `Nat.card A`, then every `A`-fixed point of `G ⧸ N` is the image of an `A`-fixed
point of `G`.

This is the core of MathComp's `coprime_quotient_cent`
(`'C_G(A) / N = 'C_(G / N)(A / N)`, for solvable `N`); see
`coprime_fixedPoints_quotient_eq` for the subgroup-equality form.  Solvability of `N`
is required (as in MathComp): the general coprime statement needs Feit–Thompson (one
of `N`, `A` odd hence solvable) or Glauberman's lemma. -/
theorem coprime_fixedPoints_quotient_surjective [Finite A] {N : Subgroup G} [N.Normal]
    [N.SMulInvariant A] [Finite N] [IsSolvable N]
    (hco : (Nat.card A).Coprime (Nat.card N)) {x : G ⧸ N}
    (hx : x ∈ FixedPoints.subgroup A (G ⧸ N)) :
    ∃ g ∈ FixedPoints.subgroup A G, QuotientGroup.mk g = x := by
  obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective x
  have hg : ∀ a : A, g⁻¹ * (a • g) ∈ N := by
    intro a
    refine QuotientGroup.eq.mp ?_
    rw [← MulAction.Quotient.smul_mk]
    exact (hx a).symm
  obtain ⟨y, hy, hfix⟩ := exists_mul_mem_fixedPoints_aux A (Nat.card N) G N le_rfl hco hg
  refine ⟨g * y, hfix, ?_⟩
  rw [QuotientGroup.mk_mul, (QuotientGroup.eq_one_iff y).mpr hy, mul_one]

/-- **Fixed points of a coprime quotient** (subgroup-equality form):
`C_G(A) N / N = C_{G ⧸ N}(A)`, stated as the image of the fixed-point subgroup under
`QuotientGroup.mk'` (which absorbs the `N` factor).

This corresponds to MathComp's `coprime_quotient_cent`. -/
theorem coprime_fixedPoints_quotient_eq [Finite A] {N : Subgroup G} [N.Normal]
    [N.SMulInvariant A] [Finite N] [IsSolvable N]
    (hco : (Nat.card A).Coprime (Nat.card N)) :
    (FixedPoints.subgroup A G).map (QuotientGroup.mk' N)
      = FixedPoints.subgroup A (G ⧸ N) := by
  refine le_antisymm ?_ fun x hx => ?_
  · rintro _ ⟨c, hc, rfl⟩
    intro a
    change a • ((c : G) : G ⧸ N) = ((c : G) : G ⧸ N)
    rw [MulAction.Quotient.smul_mk, hc a]
  · obtain ⟨g, hgfix, rfl⟩ := coprime_fixedPoints_quotient_surjective hco hx
    exact ⟨g, hgfix, rfl⟩

/-- **The coprime commutator-centralizer product decomposition** (B&G 1.6(a)): if `A`
acts coprimely on a finite solvable group `G`, then `G = [G, A] * C_G(A)`, stated as
the join being `⊤`; since `actionCommutator A ⊤` is normal
(`Subgroup.actionCommutator_normal`), the join is the setwise product
(`Subgroup.normal_mul`).

This corresponds to MathComp's `coprime_cent_prod` (which also assumes `G`
solvable). -/
theorem coprime_cent_prod [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    actionCommutator A (⊤ : Subgroup G) ⊔ FixedPoints.subgroup A G = ⊤ := by
  have hcoc : (Nat.card A).Coprime (Nat.card (actionCommutator A (⊤ : Subgroup G))) := by
    refine hco.coprime_dvd_right ?_
    have h := card_dvd_of_le (le_top : actionCommutator A (⊤ : Subgroup G) ≤ ⊤)
    rwa [card_top] at h
  rw [eq_top_iff]
  rintro g -
  -- The action on `G ⧸ [G, A]` is trivial, so the class of `g` is `A`-fixed.
  have hfix : ((g : G) : G ⧸ actionCommutator A (⊤ : Subgroup G))
      ∈ FixedPoints.subgroup A (G ⧸ actionCommutator A (⊤ : Subgroup G)) := by
    intro a
    rw [MulAction.Quotient.smul_mk]
    exact (QuotientGroup.eq.mpr (inv_mul_smul_mem_actionCommutator a (mem_top g))).symm
  -- Lift it to an `A`-fixed element `c` in the same `[G, A]`-coset as `g`.
  obtain ⟨c, hc, hceq⟩ := coprime_fixedPoints_quotient_surjective hcoc hfix
  have hmem : c⁻¹ * g ∈ actionCommutator A (⊤ : Subgroup G) := QuotientGroup.eq.mp hceq
  rw [show g = c * (c⁻¹ * g) by group]
  have h1 : FixedPoints.subgroup A G
      ≤ actionCommutator A (⊤ : Subgroup G) ⊔ FixedPoints.subgroup A G := le_sup_right
  have h2 : actionCommutator A (⊤ : Subgroup G)
      ≤ actionCommutator A (⊤ : Subgroup G) ⊔ FixedPoints.subgroup A G := le_sup_left
  exact mul_mem (h1 hc) (h2 hmem)

/-- **Coprime actions are commutator-stable** (B&G 1.6(b)): if `A` acts coprimely on
a finite solvable group `G`, then `[G, A, A] = [G, A]`.

This corresponds to MathComp's `coprime_commGid`, which also assumes `G` solvable;
the classical statement for arbitrary finite `G` requires Glauberman/Feit–Thompson
input and is out of scope. -/
theorem coprime_commutator_eq [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    actionCommutator A (actionCommutator A (⊤ : Subgroup G))
      = actionCommutator A (⊤ : Subgroup G) := by
  refine le_antisymm (actionCommutator_le_self _) ?_
  rw [actionCommutator_le]
  rintro a g -
  -- Split `g = h * c` with `h ∈ [G, A]` and `c ∈ C_G(A)`, using `coprime_cent_prod`.
  have hg : g ∈ actionCommutator A (⊤ : Subgroup G) ⊔ FixedPoints.subgroup A G := by
    rw [coprime_cent_prod hco]
    exact mem_top g
  rw [← SetLike.mem_coe, normal_mul] at hg
  obtain ⟨h, hh, c, hc, rfl⟩ := hg
  -- Then `(h * c)⁻¹ * a • (h * c)` is the generator of `[[G, A], A]` at `c⁻¹ * h * c`.
  have hca : a • c = c := hc a
  have hkey : (h * c)⁻¹ * a • (h * c)
      = (c⁻¹ * h * c)⁻¹ * a • (c⁻¹ * h * c) := by
    simp only [smul_mul', smul_inv', hca]
    group
  rw [hkey]
  refine inv_mul_smul_mem_actionCommutator a ?_
  have hconj := actionCommutator_normal.conj_mem h hh c⁻¹
  rwa [inv_inv] at hconj

open scoped IsMulCommutative in
/-- **The coprime abelian direct-product decomposition** (B&G 1.6(d)): if `A` acts
coprimely on a finite *abelian* group `G`, then `G = [G, A] × C_G(A)` as an internal
direct product.  Stated as `IsComplement'`; both factors are normal since `G` is
abelian (`Subgroup.normal_of_isMulCommutative`), so this is Mathlib's idiom for the
internal direct product.

This corresponds to MathComp's `coprime_abelian_cent_dprod`. -/
theorem coprime_abelian_cent_dprod [Finite A] [Finite G] [IsMulCommutative G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    IsComplement' (actionCommutator A (⊤ : Subgroup G)) (FixedPoints.subgroup A G) := by
  have := Fintype.ofFinite A
  -- The averaging ("norm") homomorphism `φ g = ∏ a, a • g` (well defined: `G` abelian).
  set φ : G →* G :=
    { toFun := fun g => ∏ a : A, a • g
      map_one' := by simp
      map_mul' := fun x y => by
        simp only [smul_mul']
        exact Finset.prod_mul_distrib } with hφ
  -- `[G, A]` lies in the kernel of `φ` ...
  have hker : actionCommutator A (⊤ : Subgroup G) ≤ φ.ker := by
    rw [actionCommutator_le]
    rintro a g -
    have hshift : φ (a • g) = φ g := by
      change (∏ b : A, b • a • g) = ∏ b : A, b • g
      calc (∏ b : A, b • a • g) = ∏ b : A, (b * a) • g := by
            refine Finset.prod_congr rfl fun b _ => ?_
            rw [mul_smul]
        _ = ∏ b : A, b • g := by
            simpa using Equiv.prod_comp (Equiv.mulRight a) (fun b : A => b • g)
    rw [MonoidHom.mem_ker, map_mul, map_inv, hshift, inv_mul_cancel]
  -- ... while `φ` is the `|A|`-th power map on the fixed points, which is injective
  -- there by coprimality; hence the two subgroups are disjoint.
  have hdisj : Disjoint (actionCommutator A (⊤ : Subgroup G)) (FixedPoints.subgroup A G) := by
    rw [disjoint_def]
    intro x hx1 hx2
    have hpow : φ x = x ^ Nat.card A := by
      change (∏ _a : A, _ • x) = _
      calc (∏ a : A, a • x) = ∏ _a : A, x := Finset.prod_congr rfl fun a _ => hx2 a
        _ = x ^ Nat.card A := by
            rw [Finset.prod_const, Finset.card_univ, Nat.card_eq_fintype_card]
    have hx1' : x ^ Nat.card A = 1 := by
      rw [← hpow]
      exact hker hx1
    have h1 : orderOf x ∣ Nat.card A := orderOf_dvd_of_pow_eq_one hx1'
    have h2 : orderOf x ∣ Nat.card G := orderOf_dvd_natCard x
    rw [← orderOf_eq_one_iff]
    exact Nat.dvd_one.mp (hco ▸ Nat.dvd_gcd h1 h2)
  refine isComplement'_of_disjoint_and_mul_eq_univ hdisj ?_
  rw [← normal_mul, coprime_cent_prod hco, coe_top]

/-- **Existence of `A`-invariant Hall subgroups** : if `A` acts coprimely on a finite
solvable group `G`, then `G` has an `A`-invariant Hall π-subgroup for every `π`.

This corresponds to MathComp's `coprime_Hall_exists`.  (MathComp allows `A` solvable
instead of `G` solvable via the Feit–Thompson theorem; that alternative is not
ported.) -/
theorem coprime_hall_exists (π : Set ℕ) [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    ∃ H : Subgroup G, H.IsHall π ∧ H.SMulInvariant A := by
  sorry

/-- **Conjugacy of `A`-invariant Hall subgroups**: if `A` acts coprimely on a finite
solvable group `G`, then any two `A`-invariant Hall π-subgroups of `G` are conjugate
by an `A`-fixed element.

This corresponds to MathComp's `coprime_Hall_trans`. -/
theorem coprime_hall_trans {π : Set ℕ} [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) {H K : Subgroup G}
    (hH : H.IsHall π) (hHinv : H.SMulInvariant A)
    (hK : K.IsHall π) (hKinv : K.SMulInvariant A) :
    ∃ g ∈ FixedPoints.subgroup A G, K = H.map (MulAut.conj g).toMonoidHom := by
  sorry

end CoprimeAction
