/-
Copyright (c) 2026 Ian Klatzco. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ian Klatzco
-/
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.SemidirectProduct
import OddOrder.Mathlib.GroupTheory.Hall

/-!
# Coprime action on a finite group

The coprime-action suite: the fixed-point and Hall-subgroup theory of a group `A`
acting on a finite group `G` with `(Nat.card A).Coprime (Nat.card G)`.  These lemmas
(MathComp's `coprime_quotient_cent`, `coprime_cent_prod`, `coprime_commGid`,
`coprime_abelian_cent_dprod`, `coprime_Hall_exists`, `coprime_Hall_trans`) underpin
most of the local analysis in the odd order theorem.

## The API decision

A coprime action is encoded **externally**, as
`[Group A] [Group G] [MulDistribMulAction A G]` together with an explicit coprimality
hypothesis `(Nat.card A).Coprime (Nat.card G)` (plus `[Finite A]`, `[Finite G]` as
needed).  Rationale:

* `MulDistribMulAction` is Mathlib-native: it already comes with the fixed-point
  subgroup `FixedPoints.subgroup A G` (which we use for MathComp's `'C_G(A)` — we do
  *not* define our own), the monoid homomorphisms `MulDistribMulAction.toMonoidHom`
  and `MulDistribMulAction.toMulAut`, and the quotient-action machinery in
  `Mathlib/GroupTheory/GroupAction/OfQuotient.lean`.
* It avoids fixing `A` to be a subgroup of `MulAut G`, so the same lemmas apply
  whether `A` is an abstract group, a quotient acting on fixed points, or a subgroup
  acting by conjugation.
* **Internal actions** (`A`, `G` subgroups of a common group with
  `A ≤ Subgroup.normalizer G`, the situation of MathComp's `[~: G, A]`, `'C_G(A)`)
  are recovered through the conjugation action: see
  `Subgroup.normalizerMulDistribMulAction` below for the bridge.  Further internal
  transfer lemmas are deliberately deferred to the files that need them (Task-8-adjacent).

On top of the action we introduce:

* `Subgroup.SMulInvariant A H`: the subgroup `H` is stable under the action of `A`
  (MathComp: `A \subset 'N(H)` for internal actions).  This is a class, mirroring
  `Subgroup.Normal`, so that instances can transport it (characteristic subgroups
  are invariant, quotient actions exist, an invariant subgroup is itself acted on).
* `Subgroup.actionCommutator A H`: the commutator `[H, A]` of the action, the
  subgroup generated by `g⁻¹ * (a • g)` for `g ∈ H`, `a : A`.  It is *relative*
  (it takes a subgroup argument, MathComp-style) so that the iterated commutator
  `[G, A, A]` is expressible without subtype gymnastics; the full commutator
  `[G, A]` is `Subgroup.actionCommutator A (⊤ : Subgroup G)`.
* For an invariant normal subgroup `N`, the induced `MulDistribMulAction A (G ⧸ N)`
  (through Mathlib's `MulAction.QuotientAction`) and for an invariant subgroup `H`
  the restricted `MulDistribMulAction A ↥H`, both as instances.

## Main results

All six take a coprimality hypothesis; `G` is finite throughout.

* `coprime_fixedPoints_quotient_surjective` (+ the subgroup-equality form
  `coprime_fixedPoints_quotient_eq`): for an `A`-invariant normal *solvable*
  subgroup `N` with `(Nat.card A).Coprime (Nat.card N)`, every `A`-fixed point of
  `G ⧸ N` lifts to an `A`-fixed point of `G`.  MathComp: `coprime_quotient_cent`
  (`'C_G(A) / N = 'C_(G / N)(A / N)`), which likewise assumes `N` solvable; by
  Feit–Thompson one of `N`, `A` is always solvable, but that is not available here.
* `coprime_cent_prod`: for solvable `G`, `[G, A] * C_G(A) = G`, stated as
  `actionCommutator A ⊤ ⊔ FixedPoints.subgroup A G = ⊤` (the join of a normal
  subgroup is the setwise product, `Subgroup.normal_mul`).  MathComp:
  `coprime_cent_prod`; B&G 1.6(a).
* `coprime_commutator_eq`: for solvable `G`, `[G, A, A] = [G, A]`.  MathComp:
  `coprime_commGid`, which also assumes `G` solvable (the fully general coprime
  statement needs Glauberman/Feit–Thompson input).  B&G 1.6(b).
* `coprime_abelian_cent_dprod`: for abelian `G`, `G = [G, A] × C_G(A)` as an
  internal direct product, stated as
  `IsComplement' (actionCommutator A ⊤) (FixedPoints.subgroup A G)`; both factors
  are normal (`G` is abelian), so this is Mathlib's internal-direct-product idiom.
  MathComp: `coprime_abelian_cent_dprod`; B&G 1.6(d).
* `coprime_hall_exists`: for solvable `G`, an `A`-invariant Hall π-subgroup exists.
  MathComp: `coprime_Hall_exists` (whose `solvable A` alternative via Feit–Thompson
  is not ported: we require `G` solvable, `A` arbitrary).
* `coprime_hall_trans`: any two `A`-invariant Hall π-subgroups of a solvable `G`
  are conjugate by an element of `FixedPoints.subgroup A G`.  MathComp:
  `coprime_Hall_trans`.

MathComp's `coprime_Hall_subset` and the Glauberman-lemma variants are out of scope
here and recorded as future work in `docs/NAME_MAP.md`.

The proofs of the Hall-subgroup statements transport the action to the semidirect
product `G ⋊[φ] A` (with `φ := MulDistribMulAction.toMulAut A G`), where
`A`-invariant subgroups of `G` become subgroups normalized by the `A`-factor and
the Schur–Zassenhaus and Frattini-style conjugation arguments of
`OddOrder.Mathlib.GroupTheory.SchurZassenhaus` apply.
-/

namespace Subgroup

/-!
### `A`-invariant subgroups
-/

section SMulInvariant

variable {G : Type*} [Group G]

/-- A subgroup `H` of `G` is *`A`-invariant* if it is stable under the action of every
element of `A`.  For internal actions (conjugation) this corresponds to MathComp's
`A \subset 'N(H)`. -/
class SMulInvariant (A : Type*) {G : Type*} [Group G] [SMul A G] (H : Subgroup G) :
    Prop where
  /-- The action of any `a : A` maps `H` into itself. -/
  smul_mem : ∀ (a : A) ⦃g : G⦄, g ∈ H → a • g ∈ H

/-- For a group action, an invariant subgroup contains `a • g` iff it contains `g`. -/
theorem SMulInvariant.smul_mem_iff {A : Type*} [Group A] [MulAction A G]
    {H : Subgroup G} [H.SMulInvariant A] (a : A) {g : G} : a • g ∈ H ↔ g ∈ H :=
  ⟨fun h => by simpa using SMulInvariant.smul_mem a⁻¹ h, fun h => SMulInvariant.smul_mem a h⟩

variable {A : Type*} [Group A] [MulDistribMulAction A G]

/-- Characteristic subgroups are invariant under any action by automorphisms. -/
instance (priority := 100) SMulInvariant.of_characteristic (H : Subgroup G)
    [H.Characteristic] : H.SMulInvariant A where
  smul_mem a g hg := by
    have h := characteristic_iff_le_comap.mp ‹H.Characteristic›
      (MulDistribMulAction.toMulEquiv G a)
    simpa [mem_comap] using h hg

/-- The fixed points of the action form an invariant subgroup (the action on them is
trivial). -/
instance : (FixedPoints.subgroup A G).SMulInvariant A where
  smul_mem a g hg := by rw [hg a]; exact hg

/-- An invariant subgroup of an invariant subgroup maps forward: the image under the
inclusion of an invariant subgroup is invariant.  Stated for a general equivariant
homomorphism. -/
theorem SMulInvariant.map {G' : Type*} [Group G'] [SMul A G'] {H : Subgroup G}
    [H.SMulInvariant A] (f : G →* G') (hf : ∀ (a : A) (g : G), f (a • g) = a • f g) :
    (H.map f).SMulInvariant A where
  smul_mem a g hg := by
    obtain ⟨h, hh, rfl⟩ := hg
    exact ⟨a • h, SMulInvariant.smul_mem a hh, hf a h⟩

/-- The preimage of an invariant subgroup under an equivariant homomorphism is
invariant. -/
theorem SMulInvariant.comap {G' : Type*} [Group G'] [SMul A G'] {H : Subgroup G'}
    [H.SMulInvariant A] (f : G →* G') (hf : ∀ (a : A) (g : G), f (a • g) = a • f g) :
    (H.comap f).SMulInvariant A where
  smul_mem a g hg := by
    rw [mem_comap, hf a g]
    exact SMulInvariant.smul_mem a hg

end SMulInvariant

/-!
### The induced actions on an invariant subgroup and on the quotient by an
invariant normal subgroup
-/

section InducedActions

variable {A G : Type*} [Group G]

/-- The action of `A` descends to the coset space `G ⧸ N` of an `A`-invariant
subgroup `N`. -/
instance (priority := 100) [Monoid A] [MulDistribMulAction A G] (N : Subgroup G)
    [N.SMulInvariant A] : MulAction.QuotientAction A N where
  inv_mul_mem a {g₁ g₂} h := by
    rw [← smul_inv', ← smul_mul']
    exact SMulInvariant.smul_mem a h

/-- The action of `A` on the quotient of `G` by an `A`-invariant normal subgroup, as
a `MulDistribMulAction`.  The underlying `MulAction` is Mathlib's
`MulAction.quotient`, so `MulAction.Quotient.smul_mk` applies: `a • ↑g = ↑(a • g)`. -/
instance [Monoid A] [MulDistribMulAction A G] (N : Subgroup G) [N.Normal]
    [N.SMulInvariant A] : MulDistribMulAction A (G ⧸ N) where
  __ := (inferInstance : MulAction A (G ⧸ N))
  smul_mul a x y :=
    QuotientGroup.induction_on x fun g =>
      QuotientGroup.induction_on y fun h => congrArg QuotientGroup.mk (smul_mul' a g h)
  smul_one a := congrArg QuotientGroup.mk (smul_one a)

/-- The restriction of the action of `A` to an `A`-invariant subgroup. -/
instance [Monoid A] [MulDistribMulAction A G] (H : Subgroup G) [H.SMulInvariant A] :
    MulDistribMulAction A ↥H where
  smul a g := ⟨a • ↑g, SMulInvariant.smul_mem a g.2⟩
  one_smul g := Subtype.ext (one_smul A (g : G))
  mul_smul a b g := Subtype.ext (mul_smul a b (g : G))
  smul_mul a g h := Subtype.ext (smul_mul' a (g : G) (h : G))
  smul_one a := Subtype.ext (smul_one a)

@[simp]
theorem coe_smul [Monoid A] [MulDistribMulAction A G] {H : Subgroup G}
    [H.SMulInvariant A] (a : A) (g : H) : ((a • g : H) : G) = a • (g : G) :=
  rfl

/-- **Internal-action bridge**: a subgroup `A` of `G` normalizing a subgroup `H` acts
on `H` by conjugation, recovering MathComp's internal action from the external
`MulDistribMulAction` interface.  This is a `def`, not an instance, since it depends
on the hypothesis `A ≤ normalizer (H : Set G)`. -/
abbrev normalizerMulDistribMulAction {G : Type*} [Group G] {A H : Subgroup G}
    (hAH : A ≤ normalizer (H : Set G)) : MulDistribMulAction A H :=
  MulDistribMulAction.compHom H (Subgroup.inclusion hAH)

end InducedActions

/-!
### The commutator `[H, A]` of an action

`Subgroup.actionCommutator A H` is the subgroup generated by the "commutators"
`g⁻¹ * (a • g)` of the action, for `g ∈ H`.  For the conjugation action this is the
usual commutator of subgroups.  It is defined relative to a subgroup `H` (MathComp
style) so that the iterated commutator `[G, A, A]` is
`actionCommutator A (actionCommutator A ⊤)`.
-/

section ActionCommutator

variable {G : Type*} [Group G]

/-- The commutator `[H, A]` of an action: the subgroup generated by
`g⁻¹ * (a • g)` for `g ∈ H` and `a : A`.  MathComp: `[~: H, A]` (internal form). -/
def actionCommutator (A : Type*) [SMul A G] (H : Subgroup G) : Subgroup G :=
  closure {x | ∃ (a : A) (g : G), g ∈ H ∧ x = g⁻¹ * (a • g)}

variable {A : Type*}

theorem inv_mul_smul_mem_actionCommutator [SMul A G] {H : Subgroup G} (a : A) {g : G}
    (hg : g ∈ H) : g⁻¹ * (a • g) ∈ H.actionCommutator A :=
  subset_closure ⟨a, g, hg, rfl⟩

theorem actionCommutator_le [SMul A G] {H K : Subgroup G} :
    H.actionCommutator A ≤ K ↔ ∀ (a : A), ∀ g ∈ H, g⁻¹ * (a • g) ∈ K := by
  rw [actionCommutator, closure_le]
  constructor
  · exact fun h a g hg => h ⟨a, g, hg, rfl⟩
  · rintro h x ⟨a, g, hg, rfl⟩
    exact h a g hg

/-- The commutator of the action on an invariant subgroup is contained in it. -/
theorem actionCommutator_le_self [Monoid A] [MulAction A G] (H : Subgroup G)
    [H.SMulInvariant A] : H.actionCommutator A ≤ H :=
  actionCommutator_le.mpr fun a _ hg => H.mul_mem (H.inv_mem hg) (SMulInvariant.smul_mem a hg)

/-- The full action commutator `[G, A] = actionCommutator A ⊤` is a normal subgroup:
conjugating a generator gives `y⁻¹ * (g⁻¹ * a • g) * y =
((g * y)⁻¹ * a • (g * y)) * (y⁻¹ * a • y)⁻¹`. -/
instance actionCommutator_normal [Monoid A] [MulDistribMulAction A G] :
    (actionCommutator A (⊤ : Subgroup G)).Normal := by
  constructor
  intro n hn y
  rw [show y * n * y⁻¹ = (y⁻¹)⁻¹ * n * y⁻¹ by rw [inv_inv]]
  generalize y⁻¹ = z
  induction hn using closure_induction with
  | mem x hx =>
    obtain ⟨a, g, -, rfl⟩ := hx
    have key : z⁻¹ * (g⁻¹ * a • g) * z
        = ((g * z)⁻¹ * a • (g * z)) * (z⁻¹ * a • z)⁻¹ := by
      simp only [smul_mul', mul_inv_rev]
      group
    rw [key]
    exact mul_mem (inv_mul_smul_mem_actionCommutator a (mem_top _))
      (inv_mem (inv_mul_smul_mem_actionCommutator a (mem_top _)))
  | one => simp
  | mul x y' _ _ hx hy =>
    rw [show z⁻¹ * (x * y') * z = (z⁻¹ * x * z) * (z⁻¹ * y' * z) by group]
    exact mul_mem hx hy
  | inv x _ hx =>
    rw [show z⁻¹ * x⁻¹ * z = (z⁻¹ * x * z)⁻¹ by group]
    exact inv_mem hx

/-- The commutator of the action on an invariant subgroup is invariant:
`a' • (g⁻¹ * a • g) = (a' • g)⁻¹ * ((a' * a * a'⁻¹) • (a' • g))`. -/
instance actionCommutator_smulInvariant [Group A] [MulDistribMulAction A G]
    (H : Subgroup G) [H.SMulInvariant A] : (H.actionCommutator A).SMulInvariant A := by
  constructor
  intro b n hn
  induction hn using closure_induction with
  | mem x hx =>
    obtain ⟨a, g, hg, rfl⟩ := hx
    have key : b • (g⁻¹ * a • g) = (b • g)⁻¹ * ((b * a * b⁻¹) • (b • g)) := by
      rw [smul_mul', smul_inv', mul_smul, mul_smul, inv_smul_smul]
    rw [key]
    exact inv_mul_smul_mem_actionCommutator _ (SMulInvariant.smul_mem b hg)
  | one => simp
  | mul x y _ _ hx hy =>
    rw [smul_mul']
    exact mul_mem hx hy
  | inv x _ hx =>
    rw [smul_inv']
    exact inv_mem hx

end ActionCommutator

end Subgroup

/-!
### The coprime action suite
-/

open Subgroup

section CoprimeAction

variable {A G : Type*} [Group A] [Group G] [MulDistribMulAction A G]

/-- **Fixed points lift along coprime quotients** (surjectivity form): if `N` is an
`A`-invariant normal subgroup of `G` which is finite, *solvable* and of order coprime
to `Nat.card A`, then every `A`-fixed point of `G ⧸ N` is the image of an `A`-fixed
point of `G`.

This is the core of MathComp's `coprime_quotient_cent`
(`'C_G(A) / N = 'C_(G / N)(A / N)`, for solvable `N`); see
`coprime_fixedPoints_quotient_eq` for the subgroup-equality form.  Solvability of `N`
is required (as in MathComp): the general coprime statement needs Feit–Thompson (one
of `N`, `A` odd hence solvable) or Glauberman's lemma. -/
theorem coprime_fixedPoints_quotient_surjective [Finite A] {N : Subgroup G} [N.Normal]
    [N.SMulInvariant A] [Finite N] [IsSolvable N]
    (hco : (Nat.card A).Coprime (Nat.card N)) {x : G ⧸ N}
    (hx : x ∈ FixedPoints.subgroup A (G ⧸ N)) :
    ∃ g ∈ FixedPoints.subgroup A G, QuotientGroup.mk g = x := by
  sorry

/-- **Fixed points of a coprime quotient** (subgroup-equality form):
`C_G(A) N / N = C_{G ⧸ N}(A)`, stated as the image of the fixed-point subgroup under
`QuotientGroup.mk'` (which absorbs the `N` factor).

This corresponds to MathComp's `coprime_quotient_cent`. -/
theorem coprime_fixedPoints_quotient_eq [Finite A] {N : Subgroup G} [N.Normal]
    [N.SMulInvariant A] [Finite N] [IsSolvable N]
    (hco : (Nat.card A).Coprime (Nat.card N)) :
    (FixedPoints.subgroup A G).map (QuotientGroup.mk' N)
      = FixedPoints.subgroup A (G ⧸ N) := by
  sorry

/-- **The coprime commutator-centralizer product decomposition** (B&G 1.6(a)): if `A`
acts coprimely on a finite solvable group `G`, then `G = [G, A] * C_G(A)`, stated as
the join being `⊤`; since `actionCommutator A ⊤` is normal
(`Subgroup.actionCommutator_normal`), the join is the setwise product
(`Subgroup.normal_mul`).

This corresponds to MathComp's `coprime_cent_prod` (which also assumes `G`
solvable). -/
theorem coprime_cent_prod [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    actionCommutator A (⊤ : Subgroup G) ⊔ FixedPoints.subgroup A G = ⊤ := by
  sorry

/-- **Coprime actions are commutator-stable** (B&G 1.6(b)): if `A` acts coprimely on
a finite solvable group `G`, then `[G, A, A] = [G, A]`.

This corresponds to MathComp's `coprime_commGid`, which also assumes `G` solvable;
the classical statement for arbitrary finite `G` requires Glauberman/Feit–Thompson
input and is out of scope. -/
theorem coprime_commutator_eq [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    actionCommutator A (actionCommutator A (⊤ : Subgroup G))
      = actionCommutator A (⊤ : Subgroup G) := by
  sorry

/-- **The coprime abelian direct-product decomposition** (B&G 1.6(d)): if `A` acts
coprimely on a finite *abelian* group `G`, then `G = [G, A] × C_G(A)` as an internal
direct product.  Stated as `IsComplement'`; both factors are normal since `G` is
abelian (`Subgroup.normal_of_isMulCommutative`), so this is Mathlib's idiom for the
internal direct product.

This corresponds to MathComp's `coprime_abelian_cent_dprod`. -/
theorem coprime_abelian_cent_dprod [Finite A] [Finite G] [IsMulCommutative G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    IsComplement' (actionCommutator A (⊤ : Subgroup G)) (FixedPoints.subgroup A G) := by
  sorry

/-- **Existence of `A`-invariant Hall subgroups** : if `A` acts coprimely on a finite
solvable group `G`, then `G` has an `A`-invariant Hall π-subgroup for every `π`.

This corresponds to MathComp's `coprime_Hall_exists`.  (MathComp allows `A` solvable
instead of `G` solvable via the Feit–Thompson theorem; that alternative is not
ported.) -/
theorem coprime_hall_exists (π : Set ℕ) [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) :
    ∃ H : Subgroup G, H.IsHall π ∧ H.SMulInvariant A := by
  sorry

/-- **Conjugacy of `A`-invariant Hall subgroups**: if `A` acts coprimely on a finite
solvable group `G`, then any two `A`-invariant Hall π-subgroups of `G` are conjugate
by an `A`-fixed element.

This corresponds to MathComp's `coprime_Hall_trans`. -/
theorem coprime_hall_trans {π : Set ℕ} [Finite A] [Finite G] [IsSolvable G]
    (hco : (Nat.card A).Coprime (Nat.card G)) {H K : Subgroup G}
    (hH : H.IsHall π) (hHinv : H.SMulInvariant A)
    (hK : K.IsHall π) (hKinv : K.SMulInvariant A) :
    ∃ g ∈ FixedPoints.subgroup A G, K = H.map (MulAut.conj g).toMonoidHom := by
  sorry

end CoprimeAction
