/-
Copyright (c) 2026 Ian Klatzco. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Ian Klatzco
-/
import Mathlib.GroupTheory.Complement
import Mathlib.GroupTheory.GroupAction.Quotient
import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
import OddOrder.Mathlib.GroupTheory.Hall

/-!
# Frobenius groups: semiregular actions and the internal predicate

Foundation layer for MathComp's `frobenius.v` vocabulary, which `BGsection3`/`12`/`13` and
the Peterfalvi chapters consume pervasively.  This file provides the predicates
(`Subgroup.IsSemiregular`, `Subgroup.IsSemiprime`, `Subgroup.IsFrobenius`) and their basic
API: monotonicity, symmetry, conjugation invariance, the `cent_semiregular`/`cent_semiprime`
rewriting lemmas, the malnormality characterization, and the counting facts
(`|H| ∣ |K| - 1`, coprimality, Hall-ness of kernel and complement).  Frobenius' kernel
theorem (existence of the kernel from a malnormal complement, via induced characters) is
the next task and lands in a sibling file.

## Main definitions

* `Subgroup.IsSemiregular K H` : every nontrivial element of `H` has trivial centralizer
  in `K`, i.e. `∀ h ∈ H, h ≠ 1 → centralizer {h} ⊓ K = ⊥`.  MathComp:
  `semiregular K H := {in H^#, forall x, 'C_(K)[x] = 1}` ("`H` acts regularly on `K`").
* `Subgroup.IsSemiprime K H` : every nontrivial element of `H` has the *same* centralizer
  in `K` as all of `H`: `∀ h ∈ H, h ≠ 1 → centralizer {h} ⊓ K = centralizer ↑H ⊓ K`.
  MathComp: `semiprime K H := {in H^#, forall x, 'C_(K)[x] = 'C_(K)(H)}` ("prime action").
* `Subgroup.IsFrobenius K H` : `H` is a Frobenius complement with kernel `K`, in internal
  form: `K` is a nontrivial normal complement of the nontrivial `H` and `H` acts
  semiregularly on `K`.  MathComp: `[Frobenius G = K ><| H]`.

## Shape decisions (binding for downstream BG files)

* **Centralizer-in-a-subgroup**: `'C_K(X)` is spelled `centralizer (X : Set G) ⊓ K` and
  `'C_K[x]` is `centralizer {x} ⊓ K`, matching the convention fixed in
  `CoprimeActionInternal.lean` (centralizer on the left of the `⊓`).
* **Argument order** matches MathComp: `IsSemiregular K H` reads "`H` acts semiregularly
  on `K`" — the acted-on group (the future kernel) comes first.
* **`K.Normal` is a field of `IsFrobenius`.**  MathComp's `[Frobenius G = K ><| H]`
  contains `K ><| H == G`, and MathComp's `><|` carries `H \subset 'N(K)`; with
  `K * H = G` this makes `K` normal in `G`, so the sdprod form *does* bundle normality.
  The BG usage sites rely on it: `Frobenius_proper_quotient` (BGsection3.v:46–48) forms
  the quotient `[Frobenius G / N = (K / N) ><| (R / N)]` for `N \proper K`, which needs
  `K <| G`; the partition/counting lemmas (`Frobenius_partition`, `Frobenius_dvd_ker1`,
  BGsection3.v:82) count `H`-conjugation orbits on `K^#`, which needs `H ≤ 'N(K)`.
  Normality is *not* a consequence of the other fields: in `G = S₄` with `K` a Sylow
  2-subgroup (order 8, not normal) and `H` generated by a 3-cycle, one has
  `IsComplement' K H`, both nontrivial, and `IsSemiregular K H` (a 3-cycle has
  centralizer of order 3), yet `Nat.card H = 3` does not divide `Nat.card K - 1 = 7` —
  so dropping the field would make `IsFrobenius.card_compl_dvd_card_ker_sub_one` false.
* Counting statements use `Nat.card` with `[Finite G]`, per the project policy.

## Main results

* `Subgroup.isSemiregular_iff_isSemiprime` : semiregular ↔ semiprime + trivial `'C_K(H)`
  (for `H ≠ ⊥`); the two one-directional forms `IsSemiregular.isSemiprime` (unconditional)
  and `IsSemiprime.isSemiregular` (MathComp `semiprime_regular`).
* `Subgroup.IsSemiregular.centralizer_inf_eq_bot` / `Subgroup.IsSemiprime.centralizer_inf_eq` :
  MathComp `cent_semiregular` / `cent_semiprime`, the workhorse rewriting lemmas of
  BGsection13.
* `Subgroup.IsSemiregular.symm` (MathComp `semiregular_sym`), `.mono`
  (MathComp `semiregularS`), `.map`/`.conj` (conjugation invariance).
* `Subgroup.IsFrobenius.inf_map_conj_eq_bot` and
  `Subgroup.isFrobenius_iff_inf_map_conj_eq_bot` : in a Frobenius configuration the
  complement is malnormal along the kernel (`H ⊓ H^g = ⊥` for `g ∈ K^#`), and —
  given complement + normality — malnormality is *equivalent* to semiregularity
  (`Subgroup.isSemiregular_of_forall_inf_map_conj_eq_bot` needs no hypotheses at all).
* `Subgroup.IsFrobenius.card_compl_dvd_card_ker_sub_one` : `|H| ∣ |K| - 1`
  (MathComp `Frobenius_dvd_ker1`), via the freeness of the `H`-conjugation action
  on `K \ {1}`.
* `Subgroup.IsFrobenius.coprime_card_ker_card_compl` (MathComp `Frobenius_coprime`),
  `.ker_isHall`/`.compl_isHall` (MathComp `Frobenius_ker_Hall`/`Frobenius_compl_Hall`).
* `Subgroup.isFrobenius_iff_of_prime_card` : for a prime-order complement, Frobenius ↔
  `'C_K(H) = 1` (MathComp `prime_FrobeniusP`).

## Frobenius-complement structure: `IsZGroup` coverage audit

In the odd-order proof the complement `H` always has odd order, and the classical
structure theory gives that all its Sylow subgroups are cyclic (for `p = 2` they could
also be generalized quaternion, which cannot occur at odd order).  Once "all Sylow
subgroups cyclic" is available, Mathlib's `IsZGroup`
(`Mathlib/GroupTheory/SpecificGroups/ZGroup.lean`) already covers the downstream
structure facts:

* `IsZGroup G` (every Sylow subgroup cyclic), closed under subgroups
  (`IsZGroup.of_injective`) and quotients (`IsZGroup.of_surjective`), and implied by
  squarefree order (`IsZGroup.of_squarefree`).
* Solvability: `instance [Finite G] [IsZGroup G] : IsSolvable G` (via
  `IsZGroup.commutator_lt`).
* Metacyclic structure: `IsZGroup.isCyclic_commutator`, `IsZGroup.isCyclic_abelianization`,
  `IsZGroup.coprime_commutator_index` (the commutator subgroup is a cyclic normal Hall
  subgroup), and `isZGroup_iff_exists_mulEquiv` (a finite group is a Z-group iff it is a
  semidirect product of two cyclic groups of coprime order — Hölder).
* `IsZGroup.exponent_eq_card`, and nilpotent Z-groups are cyclic.

**Missing from Mathlib** (recorded as future work in `docs/NAME_MAP.md`):

* p-groups acting semiregularly on a nontrivial group are cyclic for odd `p` — MathComp
  `odd_regular_pgroup_cyclic` (a Proposition *of* `BGsection3.v:1571`, B&G 3.9; ports
  with the M4/BG3 task).  This is the input that makes odd Frobenius complements
  Z-groups.
* The `p = 2` branch: a 2-group with a unique subgroup of order 2 is cyclic or
  generalized quaternion; no Mathlib analogue (irrelevant at odd order, recorded for
  completeness).
* Zassenhaus' classification of nonsolvable Frobenius complements (via `SL₂(𝔽₅)`);
  irrelevant at odd order.

## MathComp name map

| MathComp (`frobenius.v`) | here |
|---|---|
| `semiregular K H` | `Subgroup.IsSemiregular K H` |
| `semiprime K H` | `Subgroup.IsSemiprime K H` |
| `semiregular1l` / `semiregular1r` | `isSemiregular_bot_left` / `isSemiregular_bot_right` |
| `semiregular_sym` | `IsSemiregular.symm` |
| `semiregularS` | `IsSemiregular.mono` |
| `semiprime_regular` | `IsSemiprime.isSemiregular` |
| `cent_semiregular` | `IsSemiregular.centralizer_inf_eq_bot` |
| `cent_semiprime` | `IsSemiprime.centralizer_inf_eq` |
| `[Frobenius G = K ><| H]` | `Subgroup.IsFrobenius K H` |
| `Frobenius_semiregularP` | `IsFrobenius.mk` / `IsFrobenius.semiregular` (definitional) |
| `Frobenius_context` | `IsFrobenius.context` (and the field projections) |
| `prime_FrobeniusP` | `isFrobenius_iff_of_prime_card` |
| `Frobenius_reg_ker` | `IsFrobenius.semiregular` (+ `IsSemiregular.eq_one_of_commute`) |
| `Frobenius_reg_compl` | `IsFrobenius.semiregular_compl` |
| `Frobenius_dvd_ker1` | `IsFrobenius.card_compl_dvd_card_ker_sub_one` |
| `Frobenius_coprime` | `IsFrobenius.coprime_card_ker_card_compl` |
| `Frobenius_ker_Hall` | `IsFrobenius.ker_isHall` (+ `coprime_card_ker_index`) |
| `Frobenius_compl_Hall` | `IsFrobenius.compl_isHall` (+ `coprime_card_compl_index`) |
| `normedTI H^# G H` (malnormality) | `isFrobenius_iff_inf_map_conj_eq_bot` |
-/

namespace Subgroup

variable {G G' : Type*} [Group G] [Group G'] {K H K' H' X : Subgroup G}

/-!
### Semiregular and semiprime actions
-/

/-- `H` acts *semiregularly* on `K` (by conjugation): every nontrivial element of `H`
has trivial centralizer in `K`.  MathComp: `semiregular K H`
(`{in H^#, forall x, 'C_(K)[x] = 1}`).  No normalization hypothesis is built in;
BG statements supply `H ≤ 'N(K)` separately, exactly as MathComp does. -/
def IsSemiregular (K H : Subgroup G) : Prop :=
  ∀ h ∈ H, h ≠ 1 → centralizer {h} ⊓ K = ⊥

/-- `H` acts *semiprimely* on `K`: every nontrivial element of `H` has the same
centralizer in `K` as the whole of `H`.  MathComp: `semiprime K H`
(`{in H^#, forall x, 'C_(K)[x] = 'C_(K)(H)}`). -/
def IsSemiprime (K H : Subgroup G) : Prop :=
  ∀ h ∈ H, h ≠ 1 → centralizer {h} ⊓ K = centralizer (H : Set G) ⊓ K

/-- Membership unfolding for `IsSemiregular`: an element of `K` commuting with a
nontrivial element of `H` is trivial. -/
theorem IsSemiregular.eq_one_of_commute (hreg : IsSemiregular K H) {h k : G} (hh : h ∈ H)
    (hh1 : h ≠ 1) (hk : k ∈ K) (hc : k * h = h * k) : k = 1 := by
  have hmem : k ∈ centralizer {h} ⊓ K :=
    mem_inf.mpr ⟨mem_centralizer_singleton_iff.mpr hc, hk⟩
  rwa [hreg h hh hh1, mem_bot] at hmem

/-- Element-wise characterization of `IsSemiregular`. -/
theorem isSemiregular_iff :
    IsSemiregular K H ↔ ∀ h ∈ H, h ≠ 1 → ∀ k ∈ K, k * h = h * k → k = 1 := by
  refine ⟨fun hreg h hh hh1 k hk hc => hreg.eq_one_of_commute hh hh1 hk hc, ?_⟩
  intro hcomm h hh hh1
  rw [eq_bot_iff]
  intro k hk
  rw [mem_inf] at hk
  rw [mem_bot]
  exact hcomm h hh hh1 k hk.2 (mem_centralizer_singleton_iff.mp hk.1)

/-- Membership unfolding for `IsSemiprime`: an element of `K` commutes with a nontrivial
element of `H` iff it commutes with all of `H`. -/
theorem IsSemiprime.commute_iff (hpr : IsSemiprime K H) {h k : G} (hh : h ∈ H) (hh1 : h ≠ 1)
    (hk : k ∈ K) : k * h = h * k ↔ ∀ x ∈ H, k * x = x * k := by
  refine ⟨fun hc x hx => ?_, fun hc => hc h hh⟩
  have hmem : k ∈ centralizer {h} ⊓ K :=
    mem_inf.mpr ⟨mem_centralizer_singleton_iff.mpr hc, hk⟩
  rw [hpr h hh hh1, mem_inf] at hmem
  exact (mem_centralizer_iff.mp hmem.1 x hx).symm

/-- The trivial group acts semiregularly on anything.  MathComp: `semiregular1r`. -/
theorem isSemiregular_bot_right : IsSemiregular K (⊥ : Subgroup G) :=
  fun _ hh hh1 => absurd (mem_bot.mp hh) hh1

/-- Anything acts semiregularly on the trivial group.  MathComp: `semiregular1l`. -/
theorem isSemiregular_bot_left : IsSemiregular (⊥ : Subgroup G) H :=
  fun _ _ _ => by rw [inf_bot_eq]

/-- The trivial group acts semiprimely on anything. -/
theorem isSemiprime_bot_right : IsSemiprime K (⊥ : Subgroup G) :=
  fun _ hh hh1 => absurd (mem_bot.mp hh) hh1

/-- Anything acts semiprimely on the trivial group. -/
theorem isSemiprime_bot_left : IsSemiprime (⊥ : Subgroup G) H :=
  fun _ _ _ => by rw [inf_bot_eq, inf_bot_eq]

/-- Semiregularity is symmetric in the two subgroups, because commuting is.
MathComp: `semiregular_sym`. -/
protected theorem IsSemiregular.symm (hreg : IsSemiregular K H) : IsSemiregular H K := by
  rw [isSemiregular_iff] at hreg ⊢
  intro k hk hk1 h hh hc
  by_contra hh1
  exact hk1 (hreg h hh hh1 k hk hc.symm)

/-- Semiregularity is monotone (downwards) in both arguments.  MathComp: `semiregularS`. -/
theorem IsSemiregular.mono (hreg : IsSemiregular K H) (hK : K' ≤ K) (hH : H' ≤ H) :
    IsSemiregular K' H' := fun h hh hh1 =>
  le_bot_iff.mp ((inf_le_inf_left _ hK).trans_eq (hreg h (hH hh) hh1))

/-- Semiprimality is monotone (downwards) in the acted-on subgroup. -/
theorem IsSemiprime.mono_left (hpr : IsSemiprime K H) (hK : K' ≤ K) : IsSemiprime K' H := by
  intro h hh hh1
  have hKK' : K ⊓ K' = K' := inf_eq_right.mpr hK
  calc centralizer {h} ⊓ K' = centralizer {h} ⊓ K ⊓ K' := by rw [inf_assoc, hKK']
    _ = centralizer (H : Set G) ⊓ K ⊓ K' := by rw [hpr h hh hh1]
    _ = centralizer (H : Set G) ⊓ K' := by rw [inf_assoc, hKK']

/-- MathComp `cent_semiregular`: if `H` acts semiregularly on `K`, then any nontrivial
`X ≤ H` has trivial centralizer in `K`. -/
theorem IsSemiregular.centralizer_inf_eq_bot (hreg : IsSemiregular K H) (hXH : X ≤ H)
    (hX : X ≠ ⊥) : centralizer (X : Set G) ⊓ K = ⊥ := by
  obtain ⟨x, hxX, hx1⟩ := X.bot_or_exists_ne_one.resolve_left hX
  refine le_bot_iff.mp (le_of_le_of_eq ?_ (hreg x (hXH hxX) hx1))
  exact inf_le_inf_right _ (centralizer_le (Set.singleton_subset_iff.mpr hxX))

/-- MathComp `cent_semiprime`: if `H` acts semiprimely on `K`, then any nontrivial
`X ≤ H` has the same centralizer in `K` as `H`.  This is the workhorse rewriting lemma
of BGsection13 (`rewrite (cent_semiprime prE1 sPE1)`, e.g. BGsection13.v:493). -/
theorem IsSemiprime.centralizer_inf_eq (hpr : IsSemiprime K H) (hXH : X ≤ H) (hX : X ≠ ⊥) :
    centralizer (X : Set G) ⊓ K = centralizer (H : Set G) ⊓ K := by
  obtain ⟨x, hxX, hx1⟩ := X.bot_or_exists_ne_one.resolve_left hX
  refine le_antisymm ?_
    (inf_le_inf_right _ (centralizer_le (SetLike.coe_subset_coe.mpr hXH)))
  calc centralizer (X : Set G) ⊓ K
      ≤ centralizer {x} ⊓ K :=
        inf_le_inf_right _ (centralizer_le (Set.singleton_subset_iff.mpr hxX))
    _ = centralizer (H : Set G) ⊓ K := hpr x (hXH hxX) hx1

/-- A semiprime action restricts to a semiprime action of any nontrivial subgroup. -/
theorem IsSemiprime.of_le (hpr : IsSemiprime K H) (hXH : X ≤ H) (hX : X ≠ ⊥) :
    IsSemiprime K X := fun x hxX hx1 => by
  rw [hpr x (hXH hxX) hx1, hpr.centralizer_inf_eq hXH hX]

/-- A semiregular action is semiprime (all the element centralizers in `K` are trivial,
and so is the joint one).  Note this needs no hypotheses. -/
theorem IsSemiregular.isSemiprime (hreg : IsSemiregular K H) : IsSemiprime K H := by
  intro h hh hh1
  have hbot := hreg h hh hh1
  rw [hbot, eq_comm, ← le_bot_iff, ← hbot]
  exact inf_le_inf_right K (centralizer_le (Set.singleton_subset_iff.mpr hh))

/-- MathComp `semiprime_regular`: a semiprime action with trivial joint centralizer is
semiregular. -/
theorem IsSemiprime.isSemiregular (hpr : IsSemiprime K H)
    (hcent : centralizer (H : Set G) ⊓ K = ⊥) : IsSemiregular K H :=
  fun h hh hh1 => (hpr h hh hh1).trans hcent

/-- Semiregular = semiprime + trivial joint centralizer (for nontrivial `H`; for
`H = ⊥` semiregularity is vacuous but `'C_K(H) = K`). -/
theorem isSemiregular_iff_isSemiprime (hH : H ≠ ⊥) :
    IsSemiregular K H ↔ IsSemiprime K H ∧ centralizer (H : Set G) ⊓ K = ⊥ :=
  ⟨fun hreg => ⟨hreg.isSemiprime, hreg.centralizer_inf_eq_bot le_rfl hH⟩,
    fun ⟨hpr, hcent⟩ => hpr.isSemiregular hcent⟩

/-!
### Transport along isomorphisms and conjugation
-/

/-- Centralizers transport along group isomorphisms:
`'C(e '' s) = e '' 'C(s)` in subgroup form. -/
theorem centralizer_image (e : G ≃* G') (s : Set G) :
    centralizer (e '' s) = (centralizer s).map e.toMonoidHom := by
  ext x
  rw [mem_map_equiv, mem_centralizer_iff, mem_centralizer_iff]
  constructor
  · intro hx g hg
    apply e.injective
    rw [map_mul, map_mul, e.apply_symm_apply]
    exact hx (e g) ⟨g, hg, rfl⟩
  · rintro hx y ⟨g, hg, rfl⟩
    calc e g * x = e g * e (e.symm x) := by rw [e.apply_symm_apply]
      _ = e (e.symm x) * e g := by rw [← map_mul, hx g hg, map_mul]
      _ = x * e g := by rw [e.apply_symm_apply]

/-- Complements transport along group isomorphisms. -/
theorem IsComplement'.map (h : IsComplement' K H) (e : G ≃* G') :
    IsComplement' (K.map e.toMonoidHom) (H.map e.toMonoidHom) := by
  rw [isComplement'_def, isComplement_iff_existsUnique]
  intro g'
  obtain ⟨p, hp, hu⟩ := h.existsUnique (e.symm g')
  refine ⟨(⟨e p.1, mem_map_of_mem _ p.1.2⟩, ⟨e p.2, mem_map_of_mem _ p.2.2⟩), ?_, ?_⟩
  · change e p.1.1 * e p.2.1 = g'
    rw [← map_mul, hp, e.apply_symm_apply]
  · rintro ⟨⟨k', hk'⟩, ⟨h', hh'⟩⟩ hq
    have hq' : e.symm k' * e.symm h' = e.symm g' := by
      rw [← map_mul]
      exact congrArg e.symm hq
    have hpair := hu (⟨e.symm k', mem_map_equiv.mp hk'⟩, ⟨e.symm h', mem_map_equiv.mp hh'⟩) hq'
    have h1 : e.symm k' = p.1.1 := congrArg (fun q => q.1.1) hpair
    have h2 : e.symm h' = p.2.1 := congrArg (fun q => q.2.1) hpair
    refine Prod.ext (Subtype.ext ?_) (Subtype.ext ?_)
    · change k' = e p.1.1
      rw [← h1, e.apply_symm_apply]
    · change h' = e p.2.1
      rw [← h2, e.apply_symm_apply]

/-- Semiregularity transports along group isomorphisms. -/
theorem IsSemiregular.map (hreg : IsSemiregular K H) (e : G ≃* G') :
    IsSemiregular (K.map e.toMonoidHom) (H.map e.toMonoidHom) := by
  intro h' hh' hh1
  rw [mem_map_equiv] at hh'
  have h1 : e.symm h' ≠ 1 := fun hc => hh1 (by rw [← e.apply_symm_apply h', hc, map_one])
  have hsingle : ({h'} : Set G') = e '' {e.symm h'} := by simp
  rw [hsingle, centralizer_image, ← Subgroup.map_inf _ _ _ e.injective,
    hreg _ hh' h1, Subgroup.map_bot]

/-- Semiprimality transports along group isomorphisms. -/
theorem IsSemiprime.map (hpr : IsSemiprime K H) (e : G ≃* G') :
    IsSemiprime (K.map e.toMonoidHom) (H.map e.toMonoidHom) := by
  intro h' hh' hh1
  rw [mem_map_equiv] at hh'
  have h1 : e.symm h' ≠ 1 := fun hc => hh1 (by rw [← e.apply_symm_apply h', hc, map_one])
  have hsingle : ({h'} : Set G') = e '' {e.symm h'} := by simp
  have hcoe : ((H.map e.toMonoidHom : Subgroup G') : Set G') = e '' (H : Set G) := by
    rw [coe_map, MulEquiv.coe_toMonoidHom]
  rw [hsingle, hcoe, centralizer_image, centralizer_image,
    ← Subgroup.map_inf _ _ _ e.injective, ← Subgroup.map_inf _ _ _ e.injective,
    hpr _ hh' h1]

/-- Semiregularity is invariant under conjugation (project conjugation spelling). -/
theorem IsSemiregular.conj (hreg : IsSemiregular K H) (g : G) :
    IsSemiregular (K.map (MulAut.conj g).toMonoidHom) (H.map (MulAut.conj g).toMonoidHom) :=
  hreg.map (MulAut.conj g)

/-- Semiprimality is invariant under conjugation (project conjugation spelling). -/
theorem IsSemiprime.conj (hpr : IsSemiprime K H) (g : G) :
    IsSemiprime (K.map (MulAut.conj g).toMonoidHom) (H.map (MulAut.conj g).toMonoidHom) :=
  hpr.map (MulAut.conj g)

/-!
### The Frobenius predicate
-/

/-- `H` is a *Frobenius complement* with *kernel* `K`, internal form: `K` is a nontrivial
normal complement of the nontrivial subgroup `H`, and `H` acts semiregularly on `K`.

MathComp: `[Frobenius G = K ><| H]`.  The `><|` bundles `H \subset 'N(K)`, i.e. `K <| G`;
see the module docstring for why the `normal` field is required (the counting facts are
false without it).  MathComp's `Frobenius_semiregularP` (which B&G 3.1 defers to) is the
statement that, given the first four fields, the Frobenius property *is* semiregularity —
here that is definitional: build with `IsFrobenius.mk`, destruct with `.semiregular`. -/
structure IsFrobenius (K H : Subgroup G) : Prop where
  /-- The kernel and the complement are complements of one another. -/
  isComplement' : IsComplement' K H
  /-- The kernel is normal (bundled in MathComp's `K ><| H = G`). -/
  normal : K.Normal
  /-- The kernel is nontrivial. -/
  ker_ne_bot : K ≠ ⊥
  /-- The complement is nontrivial. -/
  compl_ne_bot : H ≠ ⊥
  /-- The complement acts semiregularly on the kernel: `'C_K[h] = 1` for `h ∈ H^#`.
  MathComp: `Frobenius_reg_ker`. -/
  semiregular : IsSemiregular K H

/-- The kernel of a Frobenius group is proper. -/
theorem IsFrobenius.ker_ne_top (h : IsFrobenius K H) : K ≠ ⊤ := fun hc =>
  h.compl_ne_bot (isComplement'_top_left.mp (hc ▸ h.isComplement'))

/-- The complement of a Frobenius group is proper. -/
theorem IsFrobenius.compl_ne_top (h : IsFrobenius K H) : H ≠ ⊤ := fun hc =>
  h.ker_ne_bot (isComplement'_top_right.mp (hc ▸ h.isComplement'))

/-- MathComp `Frobenius_context`: the destructuring bundle
`[/\ K ><| H = G, K :!=: 1, H :!=: 1, K \proper G & H \proper G]`.
(Properness in the subgroup lattice is `≠ ⊤`; normality is available as `.normal`.) -/
theorem IsFrobenius.context (h : IsFrobenius K H) :
    IsComplement' K H ∧ K ≠ ⊥ ∧ H ≠ ⊥ ∧ K ≠ ⊤ ∧ H ≠ ⊤ :=
  ⟨h.isComplement', h.ker_ne_bot, h.compl_ne_bot, h.ker_ne_top, h.compl_ne_top⟩

/-- MathComp `Frobenius_reg_compl`: the kernel also acts semiregularly on the
complement, `'C_H[k] = 1` for `k ∈ K^#` (by symmetry of commutation). -/
theorem IsFrobenius.semiregular_compl (h : IsFrobenius K H) : IsSemiregular H K :=
  h.semiregular.symm

/-- The image of a nontrivial subgroup under a group isomorphism is nontrivial. -/
theorem map_ne_bot_of_ne_bot (hK : K ≠ ⊥) (e : G ≃* G') : K.map e.toMonoidHom ≠ ⊥ := by
  intro hc
  apply hK
  rw [eq_bot_iff] at hc ⊢
  intro x hx
  have hex := hc (mem_map_of_mem e.toMonoidHom hx)
  rw [mem_bot] at hex ⊢
  exact e.injective (by rw [map_one]; exact hex)

/-- The Frobenius property transports along group isomorphisms. -/
theorem IsFrobenius.map (h : IsFrobenius K H) (e : G ≃* G') :
    IsFrobenius (K.map e.toMonoidHom) (H.map e.toMonoidHom) where
  isComplement' := h.isComplement'.map e
  normal := h.normal.map e.toMonoidHom e.surjective
  ker_ne_bot := map_ne_bot_of_ne_bot h.ker_ne_bot e
  compl_ne_bot := map_ne_bot_of_ne_bot h.compl_ne_bot e
  semiregular := h.semiregular.map e

/-- The Frobenius property is invariant under conjugation (project conjugation
spelling).  Since the kernel is normal one even has `K.map (MulAut.conj g) = K`. -/
theorem IsFrobenius.conj (h : IsFrobenius K H) (g : G) :
    IsFrobenius (K.map (MulAut.conj g).toMonoidHom) (H.map (MulAut.conj g).toMonoidHom) :=
  h.map (MulAut.conj g)

/-!
### Malnormality: the two-point-stabilizer characterization

In a Frobenius configuration (complement + normal kernel) the semiregularity of the
action is equivalent to malnormality of `H` along `K`: `H ⊓ H^g = ⊥` for every
`g ∈ K^#`.  One direction (`isSemiregular_of_forall_inf_map_conj_eq_bot`) is true with
no hypotheses at all; the other needs both the complement property and normality (they
supply the unique factorization used to compare `H` with its conjugate).  This is the
bridge Task 4 uses to state the kernel theorem in action form (two-point stabilizers of
the coset action are trivial). -/

/-- Semiregularity implies malnormality of the complement along the kernel, given
unique `K·H` factorization and normality of `K`. -/
theorem IsSemiregular.inf_map_conj_eq_bot (hreg : IsSemiregular K H)
    (hcompl : IsComplement' K H) (hnorm : K.Normal) {g : G} (hgK : g ∈ K) (hg1 : g ≠ 1) :
    H ⊓ H.map (MulAut.conj g).toMonoidHom = ⊥ := by
  rw [eq_bot_iff]
  intro x hx
  rw [mem_inf] at hx
  obtain ⟨hxH, hxmap⟩ := hx
  rw [mem_bot]
  by_contra hx1
  obtain ⟨y, hyH, hyx⟩ := mem_map.mp hxmap
  have hyx' : g * y * g⁻¹ = x := hyx
  -- rewrite `y` as the K·H factorization `(g⁻¹ * (x * g * x⁻¹)) * x`
  have hkK : x * g * x⁻¹ ∈ K := hnorm.conj_mem g hgK x
  have hfact : g⁻¹ * (x * g * x⁻¹) * x = y := by
    have hy : y = g⁻¹ * x * g := by rw [← hyx']; group
    rw [hy]; group
  -- compare with the trivial factorization `1 * y`
  obtain ⟨p, -, hu⟩ := hcompl.existsUnique y
  have e1 := hu (⟨1, K.one_mem⟩, ⟨y, hyH⟩) (one_mul y)
  have e2 := hu (⟨g⁻¹ * (x * g * x⁻¹), mul_mem (inv_mem hgK) hkK⟩, ⟨x, hxH⟩) hfact
  have hkey : (1 : G) = g⁻¹ * (x * g * x⁻¹) :=
    congrArg (fun q => q.1.1) (e1.trans e2.symm)
  -- hence `g` commutes with `x`, contradicting semiregularity
  have hconj : x * g * x⁻¹ = g := (inv_mul_eq_one.mp hkey.symm).symm
  have hcomm : g * x = x * g := (mul_inv_eq_iff_eq_mul.mp hconj).symm
  have hmem : g ∈ centralizer {x} ⊓ K :=
    mem_inf.mpr ⟨mem_centralizer_singleton_iff.mpr hcomm, hgK⟩
  rw [hreg x hxH hx1, mem_bot] at hmem
  exact hg1 hmem

/-- Malnormality of `H` along `K` implies that `H` acts semiregularly on `K`.
This direction needs no complement or normality hypotheses. -/
theorem isSemiregular_of_forall_inf_map_conj_eq_bot
    (hmal : ∀ g ∈ K, g ≠ 1 → H ⊓ H.map (MulAut.conj g).toMonoidHom = ⊥) :
    IsSemiregular K H := by
  intro h hh hh1
  rw [eq_bot_iff]
  intro k hk
  rw [mem_inf] at hk
  obtain ⟨hkc, hkK⟩ := hk
  rw [mem_bot]
  by_contra hk1
  have hcomm : k * h = h * k := mem_centralizer_singleton_iff.mp hkc
  have hmem : h ∈ H ⊓ H.map (MulAut.conj k).toMonoidHom := by
    refine mem_inf.mpr ⟨hh, mem_map.mpr ⟨h, hh, ?_⟩⟩
    change k * h * k⁻¹ = h
    rw [mul_inv_eq_iff_eq_mul, hcomm]
  rw [hmal k hkK hk1, mem_bot] at hmem
  exact hh1 hmem

/-- The complement of a Frobenius group is malnormal along the kernel:
`H ⊓ H^g = ⊥` for `g ∈ K^#`.  (MathComp expresses this as the `normedTI H^# G H`
component of the `[Frobenius G with complement H]` definition.) -/
theorem IsFrobenius.inf_map_conj_eq_bot (h : IsFrobenius K H) {g : G} (hgK : g ∈ K)
    (hg1 : g ≠ 1) : H ⊓ H.map (MulAut.conj g).toMonoidHom = ⊥ :=
  h.semiregular.inf_map_conj_eq_bot h.isComplement' h.normal hgK hg1

/-- The Frobenius predicate with semiregularity replaced by malnormality along the
kernel.  This is the action-form bridge at the strength BG needs: the further
translation to the transitive-action characterization is Task 4's kernel theorem. -/
theorem isFrobenius_iff_inf_map_conj_eq_bot :
    IsFrobenius K H ↔
      IsComplement' K H ∧ K.Normal ∧ K ≠ ⊥ ∧ H ≠ ⊥ ∧
        ∀ g ∈ K, g ≠ 1 → H ⊓ H.map (MulAut.conj g).toMonoidHom = ⊥ := by
  constructor
  · intro h
    exact ⟨h.isComplement', h.normal, h.ker_ne_bot, h.compl_ne_bot,
      fun g hg hg1 => h.inf_map_conj_eq_bot hg hg1⟩
  · rintro ⟨hcompl, hnorm, hK, hH, hmal⟩
    exact ⟨hcompl, hnorm, hK, hH, isSemiregular_of_forall_inf_map_conj_eq_bot hmal⟩

/-- MathComp `prime_FrobeniusP`: for a complement of prime order, the Frobenius
property is equivalent to `'C_K(H) = 1` (semiregularity holds as soon as the joint
centralizer is trivial, since every nontrivial element generates `H`). -/
theorem isFrobenius_iff_of_prime_card (hcompl : IsComplement' K H) (hnorm : K.Normal)
    (hK : K ≠ ⊥) (hp : (Nat.card H).Prime) :
    IsFrobenius K H ↔ centralizer (H : Set G) ⊓ K = ⊥ := by
  have hH : H ≠ ⊥ := by
    intro hc
    rw [hc, card_bot] at hp
    exact hp.one_lt.ne' rfl
  constructor
  · intro hfrob
    exact hfrob.semiregular.centralizer_inf_eq_bot le_rfl hH
  · intro hcent
    refine ⟨hcompl, hnorm, hK, hH, fun h hh hh1 => ?_⟩
    refine le_bot_iff.mp (le_of_le_of_eq (le_inf ?_ inf_le_right) hcent)
    -- `centralizer {h} ⊓ K ≤ centralizer ↑H`: `h` generates `H`
    intro k hk
    rw [mem_inf] at hk
    rw [mem_centralizer_iff]
    intro x hx
    haveI : Fact (Nat.card H).Prime := ⟨hp⟩
    have htop : zpowers (⟨h, hh⟩ : H) = ⊤ :=
      zpowers_eq_top_of_prime_card rfl fun hc => hh1 (congrArg Subtype.val hc)
    obtain ⟨n, hn⟩ := mem_zpowers_iff.mp (htop ▸ mem_top (⟨x, hx⟩ : H))
    have hxn : h ^ n = x := by
      simpa [coe_zpow] using congrArg Subtype.val hn
    have hcomm : Commute k h := mem_centralizer_singleton_iff.mp hk.1
    rw [← hxn]
    exact (hcomm.zpow_right n).eq.symm

/-!
### Counting: `|H| ∣ |K| - 1`, coprimality, Hall-ness
-/

/-- MathComp `Frobenius_dvd_ker1`: the order of a Frobenius complement divides
`|K| - 1`.  Proof: `H` acts on `K \ {1}` by conjugation (normality); semiregularity
of `K` on `H` (symmetry) makes the action free, so `K \ {1}` is a disjoint union of
orbits of size `|H|`. -/
theorem IsFrobenius.card_compl_dvd_card_ker_sub_one [Finite G] (h : IsFrobenius K H) :
    Nat.card H ∣ Nat.card K - 1 := by
  classical
  -- the conjugation action of `H` on `K \ {1}`
  letI : MulAction H {k : K // k ≠ 1} :=
  { smul := fun a x =>
      ⟨⟨(a : G) * x.1.1 * (a : G)⁻¹, h.normal.conj_mem x.1.1 x.1.2 a⟩,
        fun hc => x.2 (Subtype.ext (conj_eq_one_iff.mp (Subtype.ext_iff.mp hc)))⟩
    one_smul := fun x => by
      refine Subtype.ext (Subtype.ext ?_)
      change ((1 : H) : G) * x.1.1 * ((1 : H) : G)⁻¹ = x.1.1
      push_cast
      group
    mul_smul := fun a b x => by
      refine Subtype.ext (Subtype.ext ?_)
      change ((a * b : H) : G) * x.1.1 * ((a * b : H) : G)⁻¹ =
        (a : G) * ((b : G) * x.1.1 * (b : G)⁻¹) * (a : G)⁻¹
      push_cast
      group }
  -- the action is free, by semiregularity of `K` acting back on `H`
  have hstab : ∀ x : {k : K // k ≠ 1}, MulAction.stabilizer H x = ⊥ := by
    intro x
    rw [eq_bot_iff]
    intro a ha
    rw [MulAction.mem_stabilizer_iff] at ha
    have hconj : (a : G) * x.1.1 * (a : G)⁻¹ = x.1.1 :=
      Subtype.ext_iff.mp (Subtype.ext_iff.mp ha)
    have hx1 : x.1.1 ≠ 1 := fun hc => x.2 (Subtype.ext hc)
    have hcomm : (a : G) * x.1.1 = x.1.1 * (a : G) := mul_inv_eq_iff_eq_mul.mp hconj
    have hmem : (a : G) ∈ centralizer {x.1.1} ⊓ H :=
      mem_inf.mpr ⟨mem_centralizer_singleton_iff.mpr hcomm, a.2⟩
    rw [h.semiregular_compl x.1.1 x.1.2 hx1, mem_bot] at hmem
    rw [mem_bot]
    exact Subtype.ext hmem
  -- count: `|K| - 1 = (number of orbits) * |H|`
  have hcard : Nat.card {k : K // k ≠ 1} = Nat.card K - 1 := by
    letI : Fintype K := Fintype.ofFinite K
    rw [Nat.card_eq_fintype_card, Nat.card_eq_fintype_card,
      ← Fintype.card_subtype_eq (1 : K)]
    exact Fintype.card_subtype_compl _
  have key := Nat.card_congr (MulAction.selfEquivOrbitsQuotientProd hstab)
  rw [Nat.card_prod, hcard] at key
  exact ⟨_, key.trans (Nat.mul_comm _ _)⟩

/-- MathComp `Frobenius_coprime`: kernel and complement of a Frobenius group have
coprime orders (immediate from `|H| ∣ |K| - 1`). -/
theorem IsFrobenius.coprime_card_ker_card_compl [Finite G] (h : IsFrobenius K H) :
    (Nat.card K).Coprime (Nat.card H) := by
  have hd1 : Nat.gcd (Nat.card K) (Nat.card H) ∣ Nat.card K - 1 :=
    (Nat.gcd_dvd_right _ _).trans h.card_compl_dvd_card_ker_sub_one
  have hd : Nat.gcd (Nat.card K) (Nat.card H) ∣ 1 := by
    have hsub := Nat.dvd_sub (Nat.gcd_dvd_left (Nat.card K) (Nat.card H)) hd1
    rwa [Nat.sub_sub_self Nat.card_pos] at hsub
  exact Nat.dvd_one.mp hd

/-- The complement of a Frobenius group has order coprime to its index — MathComp
`Frobenius_compl_Hall` in the unbundled `Hall G H := coprime #|H| #|G : H|` form. -/
theorem IsFrobenius.coprime_card_compl_index [Finite G] (h : IsFrobenius K H) :
    (Nat.card H).Coprime H.index := by
  rw [h.isComplement'.index_eq_card]
  exact h.coprime_card_ker_card_compl.symm

/-- The kernel of a Frobenius group has order coprime to its index — MathComp
`Frobenius_ker_Hall` in the unbundled form. -/
theorem IsFrobenius.coprime_card_ker_index [Finite G] (h : IsFrobenius K H) :
    (Nat.card K).Coprime K.index := by
  rw [h.isComplement'.symm.index_eq_card]
  exact h.coprime_card_ker_card_compl

/-- MathComp `Frobenius_compl_Hall`, in the project's π-indexed form: the complement is
a Hall π-subgroup for π the primes of its order. -/
theorem IsFrobenius.compl_isHall [Finite G] (h : IsFrobenius K H) :
    H.IsHall ↑(Nat.card H).primeFactors := by
  refine ⟨fun p hp => Finset.mem_coe.mpr hp, fun p hpIdx hpCard => ?_⟩
  exact absurd hpIdx
    (Finset.disjoint_left.mp h.coprime_card_compl_index.disjoint_primeFactors
      (Finset.mem_coe.mp hpCard))

/-- MathComp `Frobenius_ker_Hall`, in the project's π-indexed form: the kernel is a
Hall π-subgroup for π the primes of its order. -/
theorem IsFrobenius.ker_isHall [Finite G] (h : IsFrobenius K H) :
    K.IsHall ↑(Nat.card K).primeFactors := by
  refine ⟨fun p hp => Finset.mem_coe.mpr hp, fun p hpIdx hpCard => ?_⟩
  exact absurd hpIdx
    (Finset.disjoint_left.mp h.coprime_card_ker_index.disjoint_primeFactors
      (Finset.mem_coe.mp hpCard))

/-!
### Smoke tests: the BG usage shapes

Statement-shape checks against actual MathComp usage sites, kept as documentation
(cf. the same convention in `CoprimeActionInternal.lean`).
-/

section SmokeTests

/- BGsection3.v:144–147 (`regular_pq_group_cyclic`), hypothesis line
`H :!=: 1 -> R \subset 'N(H) -> semiregular H R -> cyclic R`, and the rewrite
`rewrite -subsetIidl (cent_semiregular regHR) ?subG1` at BGsection3.v:191. -/
example {H R : Subgroup G} (_ : H ≠ ⊥) (_ : R ≤ normalizer (H : Set G))
    (regHR : H.IsSemiregular R) {X : Subgroup G} (sXR : X ≤ R) (ntX : X ≠ ⊥) :
    centralizer (X : Set G) ⊓ H = ⊥ :=
  regHR.centralizer_inf_eq_bot sXR ntX

/- BGsection13.v:334 (`tau1_primact_Msigma : ... -> semiprime M`_\sigma E1`) with its
rewrite `rewrite (cent_semiprime (tau1_primact_Msigma hallE1)) //` at BGsection13.v:376,
and the subgroup-restriction step `(cent_semiprime prE1 sPE1)` at BGsection13.v:493. -/
example {Ms E1 P : Subgroup G} (prE1 : Ms.IsSemiprime E1) (sPE1 : P ≤ E1) (ntP : P ≠ ⊥) :
    centralizer (P : Set G) ⊓ Ms = centralizer (E1 : Set G) ⊓ Ms :=
  prE1.centralizer_inf_eq sPE1 ntP

/- BGsection12.v:1666–1667: `have frobMsU: [Frobenius Ms <*> U = Ms ><| U]` by
`apply/Frobenius_semiregularP=> // e Ue` — constructing the Frobenius predicate from
the semidirect decomposition and semiregularity. -/
example {Ms U : Subgroup G} (defMsU : IsComplement' Ms U) (nsMs : Ms.Normal)
    (ntMs : Ms ≠ ⊥) (ntU : U ≠ ⊥) (regMsU : Ms.IsSemiregular U) : Ms.IsFrobenius U :=
  ⟨defMsU, nsMs, ntMs, ntU, regMsU⟩

/- BGsection3.v:51: `have [defG _ ntR _ _] := Frobenius_context frobG` — destructuring,
and BGsection3.v:66 `rewrite cent_cycle (Frobenius_reg_ker frobG)` — the semiregularity
of the kernel action extracted from the predicate. -/
example {K R : Subgroup G} (frobG : K.IsFrobenius R) :
    IsComplement' K R ∧ R ≠ ⊥ ∧ K.IsSemiregular R :=
  ⟨frobG.isComplement', frobG.compl_ne_bot, frobG.semiregular⟩

/- BGsection3.v:1297: `have frobG: [Frobenius G = K ><| R] by apply/prime_FrobeniusP`
(inside `prime_Frobenius_sol_kernel_nil`, with `#|R|` prime and `'C_K(R) = 1`). -/
example {K R : Subgroup G} (defG : IsComplement' K R) (nsK : K.Normal) (ntK : K ≠ ⊥)
    (oR : (Nat.card R).Prime) (regR : centralizer (R : Set G) ⊓ K = ⊥) :
    K.IsFrobenius R :=
  (isFrobenius_iff_of_prime_card defG nsK ntK oR).mpr regR

end SmokeTests

end Subgroup
